### ISSUE TITLE
установка на oracle 11.2.0.4

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#10]
У нас учетная система на субд oracle 11.2.0.4.
В ней встроенная  версия java: 1.5.0.51 .
Можно ли при таких условиях установить diadocsdk-1.36.2.jar ?

Уже при установке JCP на оракл (библиотек из пакета jcp.1.0.54) не все устанавливается.

**Comment by asvyazin** [comment]
С 1.5 должно работать. Что именно не устанавливается?

**Comment by Insapov** [comment]
Вот от системного администратора, то что не установилось помечено минусом.
ASN1P.jar		+
asn1rt.jar		+
CAdES.jar		-
dnsns.jar		+
forms_rt.jar		-
JCP.jar			-
JCPinst.jar		+
JCPRequest.jar		-
JCPRevCheck.jar		-
JCPRevTools.jar		-
JCPxml.jar		-
JCryptoP.jar		-
localedata.jar		-
sunjce_provider.jar	+
XMLDSigRI.jar		-




commons-codec-1.10.jar		+
commons-io-2.5-javadoc.jar	+
commons-io-2.5.jar		+
commons-logging-1.0.3.jar	-
diadocsdk-1.36.2.jar		-
httpclient-java4-4.1.2.jar	-
httpcore-java4-4.1.2.jar	+
protobuf-java4-2.4.1.jar	+

**Comment by asvyazin** [comment]
А ошибки какие?

**Comment by Insapov** [comment]
При загрузке forms_rt вылезают сообщения. Лог во вложенном файле.
Подскажите что нужно закачать еще?
[forms_rt.txt](https://github.com/diadoc/diadocsdk-java/files/393056/forms_rt.txt)

**Comment by asvyazin** [comment]
forms_rt.txt в нечитабельной кодировке.

А остальные ошибки как будто бы CryptoPro JCP не установлено в JRE...

**Comment by Insapov** [comment]
выкладываю новый вариант forms_rt
[forms_rt.txt](https://github.com/diadoc/diadocsdk-java/files/395328/forms_rt.txt)

**Comment by asvyazin** [comment]
А что такое forms_rt и зачем оно нужно для установки JCP? Просто у него, судя по всему, довольно много зависимостей, которые видимо так же придется все вручную по очереди добавлять... Это точно нужно?

**Comment by Insapov** [comment]
forms_rt,jar входит в папку с JCP

**Comment by asvyazin** [comment]
Видимо придется тогда с зависимостями разбираться...
Классы org/objectweb/asm/..., судя по всему, из библиотеки asm.jar, которая есть вот здесь: http://asm.ow2.org. Сложно сказать какая версия нужна, при обычной установке в JRE CryptoPro JCP эту библиотеку не устанавливает и работает без нее.
Классы org/jdom/..., похоже, отсюда: http://www.jdom.org, библиотека jdom, скорее всего, нужна версия 1.x, а не 2.x.
Еще в ошибках есть com/jgoodies/forms/..., они видимо отсюда: http://www.jgoodies.com/downloads/libraries/, библиотека JGoodies Forms.
