### ISSUE TITLE
проблема с commons-logging-1.0.3.jar

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#11]
У нас учетная система на субд oracle 11.2.0.4.
В ней встроенная версия java: 1.5.0.51 .
Используем loadjava
Подскажите, как победить ошибки?

errors   : class org/apache/commons/logging/impl/Log4JCategoryLog
    ORA-29521: не удалось найти ссылочное имя  org/apache/log4j/Category
    ORA-29521: не удалось найти ссылочное имя  org/apache/log4j/Priority
errors   : class org/apache/commons/logging/impl/Log4JLogger
    ORA-29521: не удалось найти ссылочное имя  org/apache/log4j/Logger
    ORA-29521: не удалось найти ссылочное имя  org/apache/log4j/Priority
errors   : class org/apache/commons/logging/impl/Log4jFactory
    ORA-29521: не удалось найти ссылочное имя  org/apache/log4j/Logger
errors   : class org/apache/commons/logging/impl/LogKitLogger
    ORA-29521: не удалось найти ссылочное имя  org/apache/log/Hierarchy
    ORA-29521: не удалось найти ссылочное имя  org/apache/log/Logger
The following operations failed
    class org/apache/commons/logging/impl/Log4JCategoryLog: resolution
    class org/apache/commons/logging/impl/Log4JLogger: resolution
    class org/apache/commons/logging/impl/Log4jFactory: resolution
    class org/apache/commons/logging/impl/LogKitLogger: resolution
exiting  : Failures occurred during processing

**Comment by asvyazin** [comment]
Видимо нужно еще добавить библиотеку log4j

**Comment by Insapov** [comment]
Получилось. Спасибо.
