### ISSUE TITLE
Открытие методов DiadocApi.ReceivePostHttpResponse  и DiadocApi.ReceiveGetHttpResponse 

### ISSUE THREAD

**Issue by VarenykhE** [diadoc/diadocsdk-java#115]
Добрый день!

Не могу вызвать метод GeneratePrintFormFromAttachment из DiadocApi (полезен для генерации форм из документов-черновиков). Приходится делать публичным метод DiadocApi.ReceivePostHttpResponse и перекомпилировать каждый раз библиотеку. Можно ли изначально сделать этот метод публичным (заодно также и ReceiveGetHttpResponse)?

**Comment by VarenykhE** [comment]
Добрый день! Можно ли как-то обсудить эту тему?

**Comment by NataliaShumikhina** [comment]
Добрый день! А в чем проблема с вызовом метода GeneratePrintFormFromAttachment?

**Comment by VarenykhE** [comment]
Добрый день!. А как его вызвать из java-обертки? Такого метода в классе Diadoc.Api.DiadocApi нет. Вы предлагаете работать с ним отдельно, также отдельно авторизуясь?

**Comment by VarenykhE** [comment]
> Добрый день! А в чем проблема с вызовом метода GeneratePrintFormFromAttachment?

Добрый день!. А как его вызвать из java-обертки? Такого метода в классе Diadoc.Api.DiadocApi нет. Вы предлагаете работать с ним отдельно, также отдельно авторизуясь?

**Comment by atytsky** [comment]
Да, нужного метода нет, но код открыт, в c# sdk есть [пример](https://github.com/diadoc/diadocsdk-csharp/blob/master/src/DiadocHttpApi.PrintAsync.cs#L14), можете сделать самостоятельно, отправите реквест – мы его примем.

**Comment by lisichka5816** [comment]
Добрый день! Почему в метод GeneratePrintFormFromAttachment передается documentType, а не к примеру messageId: идентификатор сообщения и 
documentId: идентификатор сущности документа, для которого требуется сгенерировать печатную форму; ТО есть происходит генерация печатных форм для всех документов с данным типов в ящике? или как этот процесс происходит?

Имя ресурса: /GeneratePrintFormFromAttachment
Параметры строки запроса:
documentType - тип печатной формы;
fromBoxId - идентификатор ящика инициатора пересылки документа

Или чтобы сгенерировать печатную форму для конкретного документа messageId, documentId надо указывать дополнительно?

**Comment by OlgaPetushina** [comment]
@lisichka5816 добрый день. Просто нужно использовать другой метод https://diadoc-sdk.readthedocs.io/ru/latest/http/GeneratePrintForm.html , в нем как раз сможете явно указать параметры документа, для которого нужно получить ПФ.

**Comment by VarenykhE** [comment]
> Или чтобы сгенерировать печатную форму для конкретного документа messageId, documentId надо указывать дополнительно?

Данный метод позволяет печатать документы, которых нет в Диадоке, передавая в качестве параметра xml-данные.
