### ISSUE TITLE
проблема с httpclient-java4-4.1.2

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#12]
У нас учетная система на субд oracle 11.2.0.4.
В ней встроенная версия java: 1.5.0.51 .
Используем loadjava
Подскажите, как победить ошибки, приведенные во вложенном файле?

[httpclient-java4-4.1.2.txt.txt](https://github.com/diadoc/diadocsdk-java/files/369880/httpclient-java4-4.1.2.txt.txt)

**Comment by asvyazin** [comment]
Во-первых, Java4 - это все-таки Java 1.4, надо брать версию библиотеки поновее. Во-вторых, классы, которых не хватает, находятся в библиотеке Apache httpcore, это зависимость httpclient, придется, видимо, добавить сначала ее.

**Comment by Insapov** [comment]
Получилось. Спасибо.
