### ISSUE TITLE
Не проходят никакие ответы на запросы с машин в кластере kubernates к https://diadoc-api.kontur.ru

### ISSUE THREAD

**Issue by TheElvenPath** [diadoc/diadocsdk-java#120]
Не проходят никакие ответы на запросы с машин в кластере kubernates к https://diadoc-api.kontur.ru
При этом сам адрес пингуется без проблем. С локальных машин разработчиков запросы нормально возвращают ответы.

При попытке с помощью curl сделать вызов curl (авторизации - для примера) возвращает вот что:
curl: (35) TCP connection reset by peer

Есть какие-нибудь идеи?

**Comment by antigravity** [comment]
Увы, мы помочь не сможем, поскольку не обладаем должным уровнем компетенций в kubernetes.
