### ISSUE TITLE
Странная особенность при получении документов от Диадока

### ISSUE THREAD

**Issue by analivayko** [diadoc/diadocsdk-java#129]
Получаем новые события при помощи операции GetNewEvents("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1") Во время обработки ответа видим  EventBox с id = '6cdf4c32-f3d4-4b3a-b407-8b9bfefe6f43' (MessagePath), messageId  = 'e94e9574-913c-4a35-859a-b9b34efe76c1', у которого 1 событие ( EntityType:  Signature EntityId: "cb7479d2-d4d6-47b5-bb5d-aba2193a9f8c"  ParentEntityId: "0d55ebcc-db89-4ceb-b114-ff03a6770a96" Content {  Size: -1 } AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636231833861287662 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" ) При помощи метода апи  получаем объект Message.
GetMessage("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1", true /*withOriginalSignature*/, false  /*injectEntityContent*/) У полученного объекта Message в списке Entity нет  Entity, который указан в событии. ---------- Другой пример.  В  списке событий получаем EventBox  (MessagePath) с  id=6aa685d6-3599-4af4-a4ac-1372a5166993,  messageId=c5ca64a5-65e1-4ccf-9ef1-32d4e1f40b91 В EventBox  2 entity : 1) EntityType: Attachment EntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" ParentEntityId:  "ac12a46e-1056-434f-8896-f543d8636c53" Content { Size: 5577 }  AttachmentType: RevocationRequest FileName:  "DP_PRANNUL_2BM-9640950529-964001000-201608120940264453653_2BM-9663343601-966301000-201608120924454611166_144553c1-3714-4f0b-8e22-0f0f7b4a9a06.xml"  RawCreationDate: 636294013030508056 2) EntityType: Signature  EntityId: "6c800021-3518-4727-9d24-fd1c0328ef15" ParentEntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" Content { Size: -1 }  AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636294013030875735 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" В списке entity  у полученного Message  по messageId  этих  2-х entity  также нет.  Как  найти entity из этих событий в message ? | Получаем новые события при помощи операции GetNewEvents("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1") Во время обработки ответа видим  EventBox с id = '6cdf4c32-f3d4-4b3a-b407-8b9bfefe6f43' (MessagePath), messageId  = 'e94e9574-913c-4a35-859a-b9b34efe76c1', у которого 1 событие ( EntityType:  Signature EntityId: "cb7479d2-d4d6-47b5-bb5d-aba2193a9f8c"  ParentEntityId: "0d55ebcc-db89-4ceb-b114-ff03a6770a96" Content {  Size: -1 } AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636231833861287662 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" ) При помощи метода апи  получаем объект Message. GetMessage("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1", true /*withOriginalSignature*/, false  /*injectEntityContent*/) У полученного объекта Message в списке Entity нет  Entity, который указан в событии. ---------- Другой пример.  В  списке событий получаем EventBox  (MessagePath) с  id=6aa685d6-3599-4af4-a4ac-1372a5166993,  messageId=c5ca64a5-65e1-4ccf-9ef1-32d4e1f40b91 В EventBox  2 entity : 1) EntityType: Attachment EntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" ParentEntityId:  "ac12a46e-1056-434f-8896-f543d8636c53" Content { Size: 5577 }  AttachmentType: RevocationRequest FileName:  "DP_PRANNUL_2BM-9640950529-964001000-201608120940264453653_2BM-9663343601-966301000-201608120924454611166_144553c1-3714-4f0b-8e22-0f0f7b4a9a06.xml"  RawCreationDate: 636294013030508056 2) EntityType: Signature  EntityId: "6c800021-3518-4727-9d24-fd1c0328ef15" ParentEntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" Content { Size: -1 }  AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636294013030875735 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" В списке entity  у полученного Message  по messageId  этих  2-х entity  также нет.  Как  найти entity из этих событий в message ? | Получаем новые события при помощи операции GetNewEvents("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1") Во время обработки ответа видим  EventBox с id = '6cdf4c32-f3d4-4b3a-b407-8b9bfefe6f43' (MessagePath), messageId  = 'e94e9574-913c-4a35-859a-b9b34efe76c1', у которого 1 событие ( EntityType:  Signature EntityId: "cb7479d2-d4d6-47b5-bb5d-aba2193a9f8c"  ParentEntityId: "0d55ebcc-db89-4ceb-b114-ff03a6770a96" Content {  Size: -1 } AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636231833861287662 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" ) При помощи метода апи  получаем объект Message. GetMessage("2f92723f8e3b42e4a29d34c85ea526a4@diadoc.ru",  "e94e9574-913c-4a35-859a-b9b34efe76c1", true /*withOriginalSignature*/, false  /*injectEntityContent*/) У полученного объекта Message в списке Entity нет  Entity, который указан в событии. ---------- Другой пример.  В  списке событий получаем EventBox  (MessagePath) с  id=6aa685d6-3599-4af4-a4ac-1372a5166993,  messageId=c5ca64a5-65e1-4ccf-9ef1-32d4e1f40b91 В EventBox  2 entity : 1) EntityType: Attachment EntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" ParentEntityId:  "ac12a46e-1056-434f-8896-f543d8636c53" Content { Size: 5577 }  AttachmentType: RevocationRequest FileName:  "DP_PRANNUL_2BM-9640950529-964001000-201608120940264453653_2BM-9663343601-966301000-201608120924454611166_144553c1-3714-4f0b-8e22-0f0f7b4a9a06.xml"  RawCreationDate: 636294013030508056 2) EntityType: Signature  EntityId: "6c800021-3518-4727-9d24-fd1c0328ef15" ParentEntityId:  "6321ea2c-7c05-4bff-be91-ce8d08bfa583" Content { Size: -1 }  AttachmentType: Nonformalized SignerBoxId: "893dbb087e254838bc20e7a81bd4ab84@diadoc.ru"  RawCreationDate: 636294013030875735 SignerDepartmentId:  "00000000-0000-0000-0000-000000000000" В списке entity  у полученного Message  по messageId  этих  2-х entity  также нет.  Как  найти entity из этих событий в message ?

**Comment by OlgaPetushina** [comment]
@analivayko мы готовы проконсультировать Вас, если вопрос будет задан в более структурированном и читаемом виде.  Пожалуйста, используйте встроенные  инструменты форматирования, разбиение текста на абзацы - это существенно ускорит решение проблемы. Спасибо.
