### ISSUE TITLE
предупреждение проверки достоверности

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#14]
При попытке загрузить в оракл diadocsdk-1.36.2.jar
вылезают ошибки, приведенные во вложенном файле.

[diadoc_sdk.txt](https://github.com/diadoc/diadocsdk-java/files/378138/diadoc_sdk.txt)

**Comment by asvyazin** [comment]
А до этого diadocsdk другой версии не загружался?
Или может несколько разных версий какой-нибудь зависимой библиотеки загружено, например, protobuf?

**Comment by Insapov** [comment]
Подскажите пожалуйста какие версии библиотек должны быть загружены?
protobuf вроде загружался один раз, protobuf-java4-2.4.1.jar.
А по другим библиотекам какие версии использовать? (commons-codec, ...)
Я имею ввиду для нашего случая, для java 1.5.

**Comment by asvyazin** [comment]
Вот java4 как раз и виновата. Протобуф для java 1.4 несовместим с более свежим (а именно с ним компилируется diadocsdk, видимо поэтому типы и не совпадают). Определенно надо использовать protobuf *без* java4

**Comment by Insapov** [comment]
Эту проблему удалось победить с другим протобуфом
