### ISSUE TITLE
мониторинг доступности

### ISSUE THREAD

**Issue by rnuser19** [diadoc/diadocsdk-java#140]
добрый день!
есть возможность скриптом проверять доступность сервиса диадок авторизацией без использования http-api? для чего нужно? нужно для мониторинга доступности сервиса, по требованию руководства, в мониторинге светился зелёненькая индикация ДИАДОК :))  авторизация прошла, код ОК, отконектился и ждем следующего раза часа через 2-3

**Comment by i82** [comment]
у нас нет инструментов, которые ответили бы на вопрос о доступности сервиса.
Понять работает ли сервис вы можете только сделав боевые запросы к апи
