### ISSUE TITLE
Ошибка при отправке Recipient forbids to receive messages

### ISSUE THREAD

**Issue by lshytov** [diadoc/diadocsdk-java#15]
При отправке неформализованного документа из реальной организации в тестовую через Java API получаем ошибку: Recipient forbids to receive messages from blocked senders. Sender - реальная организация, по которой нет блокировок.
2 недели назад такая отправка работала.

**Comment by atytsky** [comment]
Какой код ответа приходит от API?

Есть подозрение, что это связано с обновлением в API. Вот [новость](http://www.diadoc.ru/blog/7684). Вот [реквест](https://github.com/diadoc/diadocapi-docs/pull/41/files) с изменениями в API. В руководстве пользователя [п.8](https://wiki.diadoc.ru/pages/viewpage.action?pageId=1146900)

**Comment by lshytov** [comment]
В реквизитах организации, в которую отправляем, стоит значение "Все организации, кроме списка Заблокированные". Но эта организация имеет тестовый  статус, может быть в этом дело? Или из-за изменений в API надо передавать дополнительный статус?

**Comment by atytsky** [comment]
А список "Заблокированные" у организации, в которую отправляете пустой? Тестовый статус не должен играть никакой роли и его дополнительно не нужно никуда передавать.
