### ISSUE TITLE
Проблемы с подписанием документов

### ISSUE THREAD

**Issue by RayderXEE** [diadoc/diadocsdk-java#150]
Добрый день.

Подскажите пожалуйста. Мы используем API решение Диадок в своем приложении. Мы переходим на новые версии ПО (Java-11, JCP-2.0, diadocsdk-2.7.0) и проводим тесты. При отправке документов через наше интеграционное решение возникает ошибка при подписании.

![SignError](https://user-images.githubusercontent.com/13517268/58875414-285ec900-86d4-11e9-8f3b-0a0dac680cdc.PNG)

Если используем тестовый сертификат, выполненный по GOST3410DH подписание проходит успешно. С новыми сертификатами, выполненными по GOST3410DHEL получаем описаную выше ошибку.
Пример используемого кода:

::::::::::::::::::::::::::::::::::::::::::::::::::::::::: DiadocAdapter :::::::::::::::::::::::::::::::::::::::::::::::::

```
public abstract class DiadocAdapter {

    protected DiadocConfig config;

    protected X509Certificate certificate;		<----------------------------

    @Getter
    protected DiadocApi diadocApi;

    @Getter
    protected Organization organization;

    public DiadocAdapter(DiadocConfig config, SecurityConfig securityConfig) throws Exception {
        this.config = config;
        certificate = SecurityUtils.readDataFromFile(securityConfig.getCertificatePath());	<------
        diadocApi = new DiadocApi(config.getApiClientId(), config.getBaseDiadocUrl());
        setHttpProxy(config);
        authorize();
    }
```

:::::::::::::::::::::::::::::::::::::::::::::::::::::::: DiadocSenderAdapter :::::::::::::::::::::::::::::::::::::::::::::

```
private MessageToPost.Builder createMessageToPostNonFormalized(String senderBoxId, String receiverBoxId, Document document, boolean signed) throws Exception {
        MessageToPost.Builder messageToPost = createMessageToPost(senderBoxId, receiverBoxId);

        NonformalizedAttachment.Builder nonformalized = messageToPost.addNonformalizedDocumentsBuilder();
        nonformalized.setFileName(document.getDocumentName());
        nonformalized.setNeedRecipientSignature(signed);
        if (document.getDocumentComment() != null) {
            nonformalized.setComment(document.getDocumentComment());
        }
        if (document.getInitialDocumentIds() != null) {
            //задаем init документы (для формирования пакета у получателя)
            List<DocumentId> initialDocumentIds = getInitialDiadocDocumentIds(document);
            nonformalized.addAllInitialDocumentIds(initialDocumentIds);
        }

        ByteString content = ByteString.copyFrom(document.getDocumentContent().getDocumentContent());
        ByteString signature = ByteString.copyFrom(CertificateHelper.sign(certificate, content.toByteArray()));	<---

        SignedContent.Builder signedContent = nonformalized.getSignedContentBuilder();
        signedContent.setContent(content);
        signedContent.setSignature(signature);	<--------------------

        messageToPost.setToDepartmentId(document.getReciever().getDepId() != null ? document.getReciever().getDepId(): "");
        messageToPost.setFromDepartmentId(document.getSender().getDepId() != null ? document.getSender().getDepId() : "");

        return messageToPost;
    }
```

**Comment by alogicman** [comment]
Добрый день!
Дайте, пожалуйста, ссылку на документ, в котором не прошла проверка подписи

**Comment by RayderXEE** [comment]
https://diadoc.kontur.ru/f88aeb14-4293-4ec9-8e7b-8a9383734045/Document/Show?letterId=f6ea87eb-3d69-4856-a56c-e5c3b1007028&documentId=a083cb0b-7ef8-4aad-bcaf-bf6476f0d70f

**Comment by denxz** [comment]
с похожей проблемой переопределил в CertificateHelper - CMSSign и createCMS
в CMSSign - `Signature signature = Signature.getInstance("GOST3411_2012_256withGOST3410_2012_256");`

в createCMS - `cms.signerInfos.elements[0].digestAlgorithm = new DigestAlgorithmIdentifier(AlgIdSpec.OID_DIGEST_2012_256.value);`
                    - `cms.signerInfos.elements[0].signatureAlgorithm = new SignatureAlgorithmIdentifier(AlgIdSpec.OID_PARAMS_SIG_2012_256.value);`
с "новым" ключом подписывает

**Comment by RayderXEE** [comment]
Попробывал совет выше. Не помогло.

**Comment by Nikkkb** [comment]
Доброго дня. Есть у кого-нибудь идеи? С меня подарок!

**Comment by Nikkkb** [comment]
> Добрый день!
> Дайте, пожалуйста, ссылку на документ, в котором не прошла проверка подписи

Удалось помостреть?

**Comment by ankiycoder** [comment]
У кого нибудь получилось решить проблему? Тоже столкнулся с этой ошибкой (

**Comment by dorohovrs** [comment]
Такая же проблема. Решение построено на Java-11, JCP-2.0, diadocsdk-2.19.0. Сначала был сертификат со старым ГОСТ, подписывал без проблем. Поменял сертификат, возникла эта ошибка. 
Предложенный выше вариант решения так же не помог.

**Comment by NataliaShumikhina** [comment]
Добрый день! Мы занимаемся решение данной проблемы. Как все будет готово - сообщим.

**Comment by dorohovrs** [comment]
Есть ли понимание когда ситуация с подписанием документов прояснится? Или уже есть какое то решение?

**Comment by ThisIsBuddyRIch** [comment]
Новой версии Sdk 3.0.0 появилась поддержка ГОСТ 2012

**Comment by dorohovrs** [comment]
> Новой версии Sdk 3.0.0 появилась поддержка ГОСТ 2012

Сборка релиза будет? Отсутствует jar в релизе

**Comment by ThisIsBuddyRIch** [comment]
Прикрепил руками
