### ISSUE TITLE
Ошибка при обращении к элементам ActiveX из Win10

### ISSUE THREAD

**Issue by umnyj** [diadoc/diadocsdk-java#16]
Добрый день.

Работаем с вашим API через ActiveX. Настраивали на множестве компьютеров, но на Win10 и IE11 выходит ошибка при обращении к объектам ActiveX:

![gedckighlpndnlkj](https://cloud.githubusercontent.com/assets/20768524/17291343/5ad8023c-57f4-11e6-92e1-682557d910e7.png)

Инструкция по установке следующая (опробована на множестве компьютерах):

1.       Сохранить каталог DiadocSDK на локальном диске, открыть его и перейти в подкаталог DiadocAPI\bin
2.       На рабочем месте пользователя от имени администратора выполнить Diadoc_Reg.bat.
3.       На рабочем месте пользователя от имени администратора выполнить Diadoc_Reg64.bat.
4.       На рабочем месте пользователя от имени администратора выполнить Diadoc_Unblock.bat.
5.       На рабочем месте пользователя от имени администратора запустить файл Activate.reg.
6.       Откройте «Свойства обозревателя» интернет-браузера Internet Explorer

Также проверяем настройку «Доступ к источникам данных за пределами домена» в свойствах обозревателя, она должна иметь значение «Включить». Кроме этого, включается все, что можно, в свойствах обозревателя IE в плане ActiveX.

На тестовой странице (привел ниже) все достаточно просто, создается основа страницы, затем идет блок try catch. В нем весь процесс обрывается на строке:

var crypt = new ActiveXObject("Diadoc.Api.ComCryptApi");

Хотя вроде бы все, что можно, мы уже настроили и перепроверили десяток раз..
Посмотрите, пожалуйста, может быть, вы сталкивались с этим.
Код нашей страницы прилагаю ниже (вырезал лишнее).

[TestDiadoc.txt](https://github.com/diadoc/diadocsdk-java/files/393504/TestDiadoc.txt)

**Comment by asvyazin** [comment]
Это точно IE11, а не Edge?

Скопируйте сюда выдачу команд Diadoc_Reg.bat, Diadoc_Reg64.bat, Diadoc_Unblock.bat

И еще сделайте скриншот всего экрана, а не только alert-а

**Comment by umnyj** [comment]
Да, это именно IE11.

![1](https://cloud.githubusercontent.com/assets/20768524/17317570/5a6706b2-5890-11e6-845e-a12b399265ae.png)

![default](https://cloud.githubusercontent.com/assets/20768524/17317574/5e2afdc6-5890-11e6-83c0-030618f2098b.png)

Ниже - логи из командной строки, запущенной из-под администратора. Ошибка Reg64 обусловлена тем, что система 32-разрядная.

Microsoft Windows [Version 10.0.10586]
(c) Корпорация Майкрософт (Microsoft Corporation), 2015. Все права защищены.

C:\Windows\system32>cd C:\DiadocSDK\C#\DiadocApi\bin

C:\DiadocSDK\C#\DiadocApi\bin>diadoc_reg.bat

C:\DiadocSDK\C#\DiadocApi\bin>REM ╨хушёЄЁшЁєхЄ ёсюЁъє, ўЄюс√ Diadoc API ёЄрыю фюёЄєяэю ўхЁхч COM.

C:\DiadocSDK\C#\DiadocApi\bin>c:\Windows\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe "C:\DiadocSDK\C#\DiadocApi\bin\DiadocApi.dll" /codebase /tlb:DiadocApi.tlb
Microsoft .NET Framework Assembly Registration Utility 4.6.1038.0
для Microsoft .NET Framework 4.6.1038.0
c Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Типы зарегистрированы успешно
Сборка экспортирована в "C:\DiadocSDK\C#\DiadocApi\bin\DiadocApi.tlb"; библиотека типов зарегистрирована успешно

C:\DiadocSDK\C#\DiadocApi\bin>pause
Для продолжения нажмите любую клавишу . . .

C:\DiadocSDK\C#\DiadocApi\bin>diadoc_reg64.bat

C:\DiadocSDK\C#\DiadocApi\bin>REM ╨хушёЄЁшЁєхЄ ёсюЁъє, ўЄюс√ Diadoc API ёЄрыю фюёЄєяэю ўхЁхч COM.

C:\DiadocSDK\C#\DiadocApi\bin>c:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe "C:\DiadocSDK\C#\DiadocApi\bin\DiadocApi.dll" /codebase /tlb:DiadocApi.tlb
Системе не удается найти указанный путь.

C:\DiadocSDK\C#\DiadocApi\bin>pause
Для продолжения нажмите любую клавишу . . .

C:\DiadocSDK\C#\DiadocApi\bin>diadoc_unblock.bat

C:\DiadocSDK\C#\DiadocApi\bin>..\..\References\sysinternals\streams.exe -accepteula -d DiadocApi.dll

Streams v1.56 - Enumerate alternate NTFS data streams
Copyright (C) 1999-2007 Mark Russinovich
Sysinternals - www.sysinternals.com


C:\DiadocSDK\C#\DiadocApi\bin>pause
Для продолжения нажмите любую клавишу . . .

C:\DiadocSDK\C#\DiadocApi\bin>

**Comment by umnyj** [comment]
На двух рабочих станциях настроили корректно, на одной не получилось даже после переставленной Win10, ошибка точно такая же.
Может быть проблема с несовместимостью железа? К чему может обращаться ActiveX-объект Diadoc.Api.ComCryptApi?

**Comment by asvyazin** [comment]
При создании - ни к чему не должен обращаться, только когда уже методы вызываются

**Comment by umnyj** [comment]
Причем возможно, что просто на "голой" win10 чего-то не хватает. Включили Net Framework AS 4.6.1, не помогло. Что еще обязательно для этого объекта? Или может быть, версия фраимворка не поддерживается, нужно понижать?

**Comment by asvyazin** [comment]
DiadocApi.dll собирается для .Net 3.5. По идее на 4.6.1 тоже должно работать, но можно попробовать пониже версии повключать. Еще попробуйте запустить не в браузере, а просто создайте JS-файл со строчкой
```javascript
var api = new ActiveXObject("Diadoc.Api.ComCryptApi");
```
 и запустите его из командной строки: `cscript <имя файла>.js`

**Comment by Sash0k** [comment]
в похожем случае в windows 10 попытка запуска через cscript начинает установку .net framework 3.5
после установки проблема решается.
