### ISSUE TITLE
Нельзя использовать GetDocflows

### ISSUE THREAD

**Issue by Sash0k** [diadoc/diadocsdk-java#164]
Доброе утро.
Можете пояснить, почему метод API [GetDocflows ](http://api-docs.diadoc.ru/ru/latest/http/GetDocflows.html?highlight=GetDocflows)недоступен через java sdk?
Как понимаю, пулл-реквест #95 не был принят, и метода до сих пор нет. В документации тоже описан пример только для C#.

Мне достался на сопровождение код, где это используется, чтоб пересобрать sdk надо делать свой форк?

**Comment by alogicman** [comment]
В версии https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F2.16.2 реализованы методы для работы с DocflowV3.

Не рекомендуем использовать предыдущие версии Docflow, так как они более не поддерживаются.
