### ISSUE TITLE
Изменение КПП плательщика в ТОРГ12

### ISSUE THREAD

**Issue by VarenykhE** [diadoc/diadocsdk-java#165]
Добрый день! При формировании ТОРГ12 игнорируется значение КПП, занесенное в структуру UniversalTransferDocumentSellerTitleInfo. Значение КПП берется из реквизитов ящика. При формировании счета-фактуры или УПД такого эффекта нет. 

`UniversalTransferDocumentSellerTitleInfo.Builder builder = null;

		try {
			builder = UniversalTransferDocumentSellerTitleInfo.newBuilder();

			builder.setFunction(FunctionType.Basic);
			builder.setDocumentCreator("uk");
			builder.setCurrency(oi.getCurrency());

			builder.setDocumentNumber(oi.getNumber());
			builder.setDocumentDate(diadocService.getFormatDate(oi.getInvoiceDate()));

			ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.Builder sellerBuilder = builder
					.getSellerBuilder();

			sellerBuilder.setOrgName(seller.getFullName());
			sellerBuilder.setInn(seller.getInn());
			sellerBuilder.setKpp(seller.getKpp());
			sellerBuilder.setOrgType(OrgType.LegalEntity);
			sellerBuilder.setAddress(seller.getAddress());
			sellerBuilder.setBankName(oi.getBankBranchName());
			sellerBuilder.setBankAccountNumber(oi.getBankAccountNum());
			sellerBuilder.setCorrespondentAccount(oi.getBankCorrAccountNum());
			sellerBuilder.setBankId(oi.getBik());
			
			builder.setSeller(sellerBuilder);

			ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.Builder buyerBuilder = builder
					.getBuyerBuilder();
			buyerBuilder.setInn(oi.getContragentInn());

//вот здесь ставим свое КПП, но оно игнорируется при формировании xml
			buyerBuilder.setKpp(oi.getContragentKpp());
			
				
			buyerBuilder.setOrgType(OrgType.LegalEntity);
			buyerBuilder.setBoxId(buyer.getBoxes(0).getBoxId());
			buyerBuilder.setAddress(buyer.getAddress());

			Shipper.Builder shipperBuilder = builder.getShipperBuilder();
			shipperBuilder.setOrgInfo(sellerBuilder);
			builder.setShipper(shipperBuilder);`

                       ...........
                  //здесь выводится правильное КПП
                       logger.info("kpp-"+ builder.build().getBuyer().getKpp());
			
			gf = diadocService.getDiadocApi().GenerateUniversalTransferDocumentXmlForSeller(
					builder.build(), true);
			
			FileOutputStream fos=new FileOutputStream("d:/rrrr.xml");
			fos.write(gf.getContent());
			fos.close();
                       //в файле КПП уже неверное

Прошу посмотреть. Заранее спасибо

**Comment by vladyslav-vasyliev** [comment]
При генерации УПД с помощью метода GenerateUtdSellerTitleXml значения ИНН-КПП в результирующем файле будут:
- те, которые были заданы с помощью setInn и setKpp тогда, когда указано значение OrgName;
- подгружены из хранилища по указанному boxId организации тогда, когда значение OrgName не указано.

При формировании СФ и УПД методом GenerateUtdSellerTitleXml логика работы такая же. Если у Вас работает иначе, то для разбора и воспроизведения ситуации прошу привести пример кода, входные данные и результирующий файл.

В приведённом Вами коде у buyerBuilder не устанавливается значение OrgName, а значит указанные ИНН и КПП будут проигнорированы, и будут использованы значения ассоциированные в Диадоке с указанным boxId.

**Comment by VarenykhE** [comment]
Да, Для формирования ТОРГ12 установил явным образом buyerBuilder.setOrgName. Все получилось.
Большое спасибо
