### ISSUE TITLE
Работа с Токенами

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#17]
Добрый день. подскажите, реализует ли АПИ работу с токенами (то есть с ключами, расположенными локально у пользователя) ? или только облачная подпись? Диадок обычный реализует.

**Comment by asvyazin** [comment]
В каждом конкретном SDK есть свои средства для работы с электронной подписью. Например, в Java SDK это класс CertificateHelper, который реализован на основе CryptoPro JCP. Работа с локальными ключами поддерживается. Правда у CryptoPro JCP есть свои особенности, например, https://github.com/diadoc/diadocsdk-java/issues/1

**Comment by faraon248** [comment]
Добрый день. нашли такое описание процедуры входа  (взято от сюда http://wiki.diadoc.ru/pages/viewpage.action?pageId=720902) :
Встроенное изображение 1
возник вопрос- требования по авторизации через API- для полноценной работы обязательно использование сертификата? 
или возможна полноценная работа с парой логин/пароль? (при отправке которых обратно получаем сессионный ключ. который далее и используем для идентификации передаваемого материала) или все таки сессионные ключи будут разные с разными правами в зависимости от типа авторизации?
