### ISSUE TITLE
Задать proxy в v 3.0

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#176]
В версии 1.* и 2.* proxy можно было задать следующим образом. Метод был deprecated, но работал.
```java
DiadocApi connectApi = new DiadocApi(KEY_DEVELOPER, DEFAULT_API_URL);
HttpHost proxy = new HttpHost(PROXY_URL, PROXY_PORT);
connectApi.setHttpParameter(ConnRoutePNames.DEFAULT_PROXY, proxy);
```
В 3.0 этот метод был удален. Подскажите, как задать proxy?

**Comment by ThisIsBuddyRIch** [comment]
Добрый день, добавим настройку прокси ближайшее время, вероятно завтра в мастере будет

**Comment by ThisIsBuddyRIch** [comment]
https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F3.0.2

Прокинул настройки прокси в конструктор DiadocApi.

**Comment by WhiteBSco** [comment]
Добавился только параметр @Nullable HttpHost proxyHost. А как быть если прокси использует аутентификацию?

**Comment by ThisIsBuddyRIch** [comment]
Добрый день, покажите как вы задавали аутентификацию для прокси в предыдущей версии.

**Comment by WhiteBSco** [comment]
Прошлой версией не пользовались, лично для меня это первый опыт использования данного API, начал с текущей версии.
Но предполагаю что надо добавить использование чего то вроде этого :

Authenticator.setDefault(new Authenticator() {
            @Override
            public PasswordAuthentication getPasswordAuthentication() {
                if (getRequestorType() == RequestorType.PROXY) {
                    String prot = getRequestingProtocol().toLowerCase();
                    String host = System.getProperty(prot + ".proxyHost", proxyHost);
                    String port = System.getProperty(prot + ".proxyPort", String.valueOf(proxyPort));
                    String user = System.getProperty(prot + ".proxyUser", proxyUser);
                    String password = System.getProperty(prot + ".proxyPassword", proxyPassword);
                    if (getRequestingHost().equalsIgnoreCase(host)) {
                        if (Integer.parseInt(port) == getRequestingPort()) {
                            return new PasswordAuthentication(user, password.toCharArray());
                        }
                    }
                }
                return null;
            }
        });

**Comment by halex2005** [comment]
Предполагаю, что вам подойдет локальный прокси [cntlm](http://cntlm.sourceforge.net/).

Как это могло бы выглядеть:

- на машине, где нужна аутентификация по логину/паролю, поставьте cntlm и настройте логин/пароль в его конфигурации
- в конфигурации приложения укажите, чтобы оно ходило на локальный прокси cntlm который вы настроили (по умолчанию это `localhost:3128`)
- cntlm будет проксировать запросы на ваш прокси с авторизацией

**Comment by eremenkoKS** [comment]
Можно попробовать вот так
 ```
       if (proxyType != null){
            logger.info("Proxy auth type: {}", proxyType);
            logger.info("Set proxy Auth with user: {}", proxyUser);
            switch (proxyType) {
                case "BASIC":
                    api.getAuthManager().getCredentialsProvider().setCredentials(
                            new AuthScope(getProxyHost(), getProxyPort()),
                            new UsernamePasswordCredentials(getProxyUser(), getProxyPassword()));
                    break;
                case "NTLM":
                    final String workstation = getWorkstation();
                    logger.info("Proxy: workstation is {}", workstation);
                    api.getAuthManager().getCredentialsProvider().setCredentials(
                            new AuthScope(getProxyHost(), getProxyPort()),
                            new NTCredentials(proxyUser, proxyPassword, workstation, proxyDomain));
                    break;
                default:
            }
        } else {
            logger.info("Proxy not set");
        }
        api.getAuthClient().authenticate(login, password);

```

**Comment by chudok** [comment]
Добрый день! Подскажите, нет ли планов добавить возможность настройки аутентификации прокси?

**Comment by ilzag** [comment]
> Добрый день! Подскажите, нет ли планов добавить возможность настройки аутентификации прокси?

Добрый день!
Нет, на данный момент таких планов нет. Записали в качестве пожелания, возможно, реализуем, но пока каких-то сроков назвать не можем.
