### ISSUE TITLE
Не передается значение вида деятельности по ОКДП

### ISSUE THREAD

**Issue by VarenykhE** [diadoc/diadocsdk-java#177]
Добрый день!
Формирую ТОРГ12 в формате 820. Клиент требует заполнение поля вида деятельности по ОКДП. Хотя это поле имеется в схеме упрощенного xml, однако его заполнение ничего не дает. При генерации накладной данных по ОКДП в ней нет

Пример упрощенного xml (пробовал вставить ОКДП везде, где только можно)
[temp.txt](https://github.com/diadoc/diadocsdk-java/files/4115725/temp.txt)

Результат
![1](https://user-images.githubusercontent.com/22496580/73153207-c173a180-40f4-11ea-9fa9-36bd6978d8bf.png)

Прошу прокомментировать данную проблему

**Comment by NataliaShumikhina** [comment]
Добрый день! В 820 формате не предусмотрено поле ОКДП, поэтому оно и не появляется в xml титула после генерации. В упрощенном xml это поле осталось со времен старого формата ТОРГ № 172, но по факту в 820 формате не используется
