### ISSUE TITLE
Можно ли получить подпись отправителя в бинарном виде?

### ISSUE THREAD

**Issue by kilbeggan** [diadoc/diadocsdk-java#178]
Здравствуйте. Хотим подтягивать к себе в систему входящие документы с подписями отправителей в бинарном виде (чтобы иметь возможность проверить подпись в своей системе). По факту видим, что доступны только статусы подписей (sender и proxy), что вызывает вопросы.

1. Всё ли мы правильно поняли и для входящего документа подписи в бинарном виде действительно недоступны?

2. В какой момент формируется статус подписи отправителя? Потому что есть "SenderSignatureUnchecked - подпись отправителя еще не проверена", намекающий на возможные варианты.

3. Фиксируется ли время проверки в каком-либо поле (не нашел)?

4. Есть способ инициировать проверку подписей через API (например, форсировать проверку при SenderSignatureUnchecked)?

5. Чисто гипотетически, можно ли надеяться на реализацию нового метода getSignatures() возвращающего все подписи в виде нового Signature, где, в простейшей форме, есть возможность получить подпись в бинарном виде? Можно даже без детализации в виде SenderSignature, ProxySignature и т.п. Также можно отдавать вообще все подписи, включая собственную как отправителя (лишним не будет). Или это категорически невозможно?

**Comment by kilbeggan** [comment]
Подписи в бинарном виде нашли в результатах PrintFormClient.generateDocumentZip(). Были бы признательны за ваши комментарии по вопросам 2, 3 и 4.

**Comment by aeremina88** [comment]
Добрый день!
> 2. В какой момент формируется статус подписи отправителя? Потому что есть "SenderSignatureUnchecked - подпись отправителя еще не проверена", намекающий на возможные варианты.

Статус подписи есть сразу после постинга документа. После отправки документа контрагенту запускается процесс проверки подписи - SenderSignatureUnchecked. После проверки статус в зависимости от результата: SenderSignatureCheckedAndValid или SenderSignatureCheckedAndInvalid. 

>4. Есть способ инициировать проверку подписей через API (например, форсировать проверку при SenderSignatureUnchecked)?

Такой возможности нет, проверка выполняется автоматически на стороне Диадока

**Comment by kilbeggan** [comment]
Спасибо большое!

**Comment by alogicman** [comment]
Контент любой сущности из сообщений можно получить с помощью метода https://api-docs.diadoc.ru/ru/latest/http/GetEntityContent.html. Метод GenerateDocumentZip позволяет скачать документ и подписи к нему или весь документооборот полностью

**Comment by kilbeggan** [comment]
Спасибо, сразу не разглядели.
