### ISSUE TITLE
Загрузка документа (doc, pdf) из вне

### ISSUE THREAD

**Issue by paveloso** [diadoc/diadocsdk-java#181]
Добрый день! Имеется ли возможность загрузить документ (doc, pdf) в систему диадока по HTTP API из вне?

Допустим, в стороннем ПО пользователь загружает документ (doc, pdf), затем это ПО отправляет этот документ в систему диадока и дальше уже можно работать с этим документом так же через стороннее ПО - открывать документ на стороне пользователя ПО, подписывать, загружать обратно подписанный документ и сверять кем и подписан ли документ вообще?

Благодарю за ответ.

**Comment by agarochka** [comment]
Добрый день.
Если это стороннее ПО наладит интеграцию с Диадоком через API Диадока https://api-docs.diadoc.ru/ru/latest/, то можно.

**Comment by paveloso** [comment]
@agarochka подскажите, пожалуйста, как это происходит и по возможности, тыкните в метод. Как преобразуется файл и как отправляется в систему диадок?

И правильно ли я понимаю, что для работы через HTTP API необходимо приобрести КриптоПро JCP?

**Comment by i82** [comment]
Добрый день.
К сожалению, в рамках обращения на гитхаб мы не сможем с должным уровнем качества проконсультировать вас по созданию интеграции с Диадоком с нуля, мы можем ответить только на вопросы о конкретных проблемах. Для получения консультаций рекомендую обратиться к вашему менеджеру, который поможет вам организовать консультации с выделенным специалистом, который будет учитывать все особенности вашей организации.

Отвечая на ваши вопросы - описание работы с неформализованными документами есть в [документации](https://api-docs.diadoc.ru/ru/latest/docflows/NonformalizedDocflow.html).
КриптоПро JCP необходимо для подписания документов, если вы работаете на Java.
