### ISSUE TITLE
Ошибка при отправке подписанного документа

### ISSUE THREAD

**Issue by WhiteBSco** [diadoc/diadocsdk-java#184]
Добрый день. При отправке подписанного сообщения получаем ошибку Diadoc.Api.exceptions.DiadocSdkException: org.apache.http.client.HttpResponseException: Bad Request
Если отправить сообщение без добавления подписи signedContentBuilder.setContent, то все уходит корректно, но документ конечно не подписанный. 

Подскажите в чем может быть проблема? Подписываем выданным Контуром сертификатом.
Запрос был сделан 2020/04/20 14:57:57:057 (МСК), ящик отправителя "62f0a60a-3946-4780-bd42-5fd27ad39e8a". Ниже код

```
public static void main(String[] args) throws DiadocSdkException {

        String defaultApiUrl = "https://diadoc-api.kontur.ru";
        String defaultClientId = "..........";  //ключ разработчика
        String user = ".....@.....ru";  //учетка для авторизации
        String password = "......";

        String fromBoxId = "62f0a60a-3946-4780-bd42-5fd27ad39e8a";
        String toBoxId = "..........";

        DiadocApi api = new DiadocApi(defaultClientId, defaultApiUrl);
        api.getAuthClient().authenticate(user, password);

        DiadocMessage_PostApiProtos.MessageToPost.Builder messageBuilder = DiadocMessage_PostApiProtos.MessageToPost.newBuilder();
        messageBuilder.setFromBoxId(fromBoxId);
        messageBuilder.setToBoxId(toBoxId);

        byte[] decbytes = "........".getBytes();  //СФ для подписания

        DiadocMessage_PostApiProtos.SignedContent.Builder signedContentBuilder = DiadocMessage_PostApiProtos.SignedContent.newBuilder();
        signedContentBuilder.setContent(ByteString.copyFrom(decbytes));

        //подпишем
        Certificate certificate = CryptoTools.loadCertificate(alias);   //сертификат получаем из hdImageStore
        byte[] sign_ = CertificateHelper.sign((X509Certificate) certificate, decbytes, password);  //password установлен при копировании сертификата

        signedContentBuilder.setSignature(ByteString.copyFrom(signature));

        DiadocMessage_PostApiProtos.XmlDocumentAttachment.Builder attachmentBuilder = DiadocMessage_PostApiProtos.XmlDocumentAttachment.newBuilder();
        attachmentBuilder.setSignedContent(signedContentBuilder.build());
        attachmentBuilder.setCustomDocumentId("test");
        messageBuilder.addInvoices(attachmentBuilder.build());

        DiadocMessage_PostApiProtos.MessageToPost messageToPost = messageBuilder.build();
        DiadocMessage_GetApiProtos.Message postedMessage = api.getMessageClient().postMessage(messageToPost);
        System.out.println(postedMessage.getMessageId());

}
```

**Comment by NataliaShumikhina** [comment]
В логах в это время по указанному ящику вижу вот такую ошибку "Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдОтпр;Невозможно получить данные по ключу: /Файл/СвУчДокОбор/@ИдПол"
Дело не в подписи, а в том, что контент xml-файла не валидный, в нем нет обязательных атрибутов.
Если отправлять документ без подписи как DelaySend (исходящий неотправленный), то данные атрибуты могут быть не указаны. После потинга в диадок они могут быть пропатчены и заполнены.

**Comment by WhiteBSco** [comment]
Огромное спасибо за ответ. 
Да, действительно, не заметили эту оплошность. Но добавление корректных @ИдПол и @ИдОтпр не исправило ситуацию. Можете ответить на несколько вопросов:
1) Что не хватает на это раз? Запрос был 2020/04/21 10:17:16:998 (МСК), ящик отправителя "62f0a60a-3946-4780-bd42-5fd27ad39e8a"
2) Можно ли как то получать более внятную ошибку чем Bad Request?
3) Есть ли какой то метод который "дозаполняет" недостающие реквизиты? Т.к. если наш файл загрузить ручками через web-интерфейс и потом снова выгрузить, они идентичны, различий нет.

**Comment by OlgaPetushina** [comment]
1. По данным логов
ErrorCode: DocumentService.InvalidFileContent(Http.BadRequest), SystemMessage: MessageToPost.Invoices[0]: {
	Location = Line: 1,
	Position: 3,
	Message = Первая строка файла должна иметь вид <  ? xml version = "1.0" encoding = "windows-1251" ?  >
}; {
	Location = Line : 3,
	Position : 6,
	/Файл[1]/СвУчДокОбор[1] / СвОЭДОтпр[1] /  @ НаимОрг,
	Message = The required attribute 'НаимОрг' is missing.
}; {
	Location = Line: 3,
	Position: 6,
	/Файл[1]/СвУчДокОбор[1] / СвОЭДОтпр[1] /  @ ИННЮЛ,
	Message = The required attribute 'ИННЮЛ' is missing.
}; {
	Location = Line: 3,
	Position: 6,
	/Файл[1]/СвУчДокОбор[1] / СвОЭДОтпр[1] /  @ ИдЭДО,
	Message = The required attribute 'ИдЭДО' is missing.
}; {
	Location = Line: 45,
	Position: 8,
	/Файл[1]/Документ[1] / Подписант[1] / ЮЛ[1] /  @ Должн,
	Message = The required attribute 'Должн' is missing.
}; {
	Location = Line: 46,
	Position: 10,
	/Файл[1]/Документ[1] / Подписант[1] / ЮЛ[1] / ФИО[1] /  @ Фамилия,
	Message = The required attribute 'Фамилия' is missing.
}; {
	Location = Line: 46,
	Position: 10,
	/Файл[1]/Документ[1] / Подписант[1] / ЮЛ[1] / ФИО[1] /  @ Имя,
	Message = The required attribute 'Имя' is missing.
}; {
	Location = /Файл/ @ ИдФайл,
	Message = Значение атрибута @ ИдФайл имеет неверный формат: ON_NSCHFDOPPR_2BM - 9672598451 - 967201000 - 202003131048193674715_2BM - 9670389950 - 967001000 - 202003160533019011277_20200415_000000000000000000000000009648346178( @ ИдОтпр = 2BM - 9672598451 - 967201000 - 202003131048193674715,  @ ИдПол = 2BM - 9670389950 - 967001000 - 202003160533019011277)
		При отстутствии / Файл / Документ / ТаблСчФакт / СведТов / ДопСведТов / НомСредИдентТов и / Файл / Документ / ТаблСчФакт / СведТов / ДопСведТов / СведПрослеж значение @ ИдФайл должно начинаться с ON_NSCHFDOPPR_,
	ON_NSCHFDOPPOKMARK_ или ON_NSCHFDOPPOKPROS
`
3. https://api-docs.diadoc.ru/ru/latest/http/PrepareDocumentsToSign.html

**Comment by WhiteBSco** [comment]
Чтобы добавить подписанта в файл пытаюсь выполнить PrepareDocumentsToSign, но получаю ошибку Bad Request.
К примеру, запрос был 2020/05/26 08:36:46:221 (МСК), ящик отправителя "62f0a60a-3946-4780-bd42-5fd27ad39e8a"

```
byte[] decbytes = ... //СФ

//делаем черновик
MessageToPost.Builder messageBuilder = MessageToPost.newBuilder();
messageBuilder.setFromBoxId(fromBoxId);
messageBuilder.setToBoxId(toBoxId);
messageBuilder.addInvoices(XmlDocumentAttachment.newBuilder()
                              .setSignedContent(SignedContent.newBuilder()
                                                 .setContent(ByteString.copyFrom(decbytes))
                                                 .build())
                              .setCustomDocumentId("test")
                              .build());
messageBuilder.setIsDraft(true);

//постим черновик
Message postedMessage = api.getMessageClient().postMessage(messageBuilder.build());

//подготавливаем документ для патча
DocumentToPatch documentToPatch = DocumentToPatch.newBuilder()
                .setDocumentId(DocumentId.newBuilder()
                                     .setMessageId(postedMessage.getMessageId())
                                     .setEntityId(postedMessage.getEntities(0).getEntityId())
                                     .build())
                .addExtendedSigner(ExtendedSigner.newBuilder()
                                     .setBoxId(fromBoxId)
                                     .setSignerCertificate(ByteString.copyFrom(cert))  //сертификат в DER кодировке
                                     .build())
                .build();
        
//формируем запрос
PrepareDocumentsToSignRequest documentsToSignRequest = PrepareDocumentsToSignRequest.newBuilder()
                                                                    .setBoxId(fromBoxId)
                                                                    .addDocuments(documentToPatch)
                                                                    .build();

PrepareDocumentsToSignResponse docToSign = api.getDocumentClient().prepareDocumentsToSign(documentsToSignRequest);
```

**Comment by WhiteBSco** [comment]
Разобрался. В настройках организации не были настроены данные по сертификату для сотрудника. Настроил через личный кабинет, все заработало.

**Comment by WhiteBSco** [comment]
Теперь при выполнении postMessagePatch получаю ошибку org.apache.http.client.HttpResponseException: Not Found.
В чем может быть причина? Все вроде верно.

2020/05/26 14:01:15:172 (МСК), ящик отправителя "62f0a60a-3946-4780-bd42-5fd27ad39e8a"

```
PrepareDocumentsToSignResponse docToSign = api.getDocumentClient().prepareDocumentsToSign(documentsToSignRequest);

//получаем дополненный контент и подписываем
DocumentPatchedContent documentPatchedContent = docToSign.getDocumentPatchedContents(0);
byte[] decbytes = documentPatchedContent.getContent().toByteArray();
byte[] sign_data = sign(decbytes);  //подписываем 

//дополним сообщение подписью и отправим
MessagePatchToPost.Builder messagePatchBuilder = MessagePatchToPost.newBuilder()
                .setBoxId(fromBoxId)
                .setMessageId(postedMessage.getMessageId())
                .addSignatures(DocumentSignature.newBuilder()
                                      .setParentEntityId(postedMessage.getEntities(0).getEntityId())
                                      .setSignature( ByteString.copyFrom(sign_data) )
                                      .setPatchedContentId(documentPatchedContent.getPatchedContentId())
                                      .build());
MessagePatch postedMessagePatch = api.getMessageClient().postMessagePatch(messagePatchBuilder.build());
```

**Comment by WhiteBSco** [comment]
Разобрался. Зря делал сообщение как черновик, т.е. лишняя строка:
`messageBuilder.setIsDraft(true);`
Зато теперь есть полный пример отправки подписанной СФ на Java :)
