### ISSUE TITLE
Статусы документов

### ISSUE THREAD

**Issue by WhiteBSco** [diadoc/diadocsdk-java#187]
Есть ли метод или какой то иной способ получения статусов документов которые отображаются в личном кабинете?
![Снимок](https://user-images.githubusercontent.com/50902831/83108909-877dd080-a0d1-11ea-8ab4-ffdaea461da5.JPG)

**Comment by ichechulina** [comment]
Статус документа можно узнать, читая ленту событий https://diadoc-sdk.readthedocs.io/ru/latest/API_Events.html

**Comment by WhiteBSco** [comment]
Я так понимаю, что статусы можно определять анализируя RecipientReceiptMetadata, ConfirmationMetadata, AmendmentRequestMetadata документа.
Но это же как уже реализовано для веб-кабинета. Ожидается ли перенос данного функционала в API? Думаю, это многими востребовано.

**Comment by i82** [comment]
перенос статуса "как в веб-интерфейсе" в апи не планируется
