### ISSUE TITLE
Авторизация через API

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#19]
Добрый день. нашли такое описание процедуры входа (взято от сюда http://wiki.diadoc.ru/pages/viewpage.action?pageId=720902) :
по нему в зависимости от типа авторизации выдаются разные права.
возник вопрос- требования по авторизации через API- для полноценной работы обязательно использование сертификата? 
или возможна полноценная работа с парой логин/пароль? (при отправке которых обратно получаем сессионный ключ. который далее и используем для идентификации передаваемого материала) или все таки сессионные ключи будут разные с разными правами в зависимости от типа авторизации?

**Comment by faraon248** [comment]
прошу помочь также  с вопросами:
1. в API Диадока описана работа с облачной подписью- то есть физически подпись хранится у Вас на сервере, и по команде от пользователя вы ее подписываете загруженный документ.
Является ли такая подпись усиленной квалификационной- то есть можно ли ее использовать для подписания счетов-фактур?
2. если пользователь хочет пользоваться своей ЭПЦ. которая хранится у него локально на защищенном носителе (токене)- какая процедура регистрации этой ЭЦП у вас в системе. чтобы вы могли проверять ее подлинность?.
2. при работе с локальной ЭЦП в каком виде происходит загрузка документа через API? сам документ команда на подпись локальным ключом (использую плагин КриптоПро и локальную версию программы CSP)? или в API передается уже подписанный документы (используя тот же плагин и ПО от КриптоПро)?

**Comment by atytsky** [comment]
1. Так как криптографические операции происходят на локальных машинах, то полноценная работа с API возможно и через пару логин/пароль. Права хранятся в привязке к сотруднику орагнизации и не зависят от типа авторизации. Подробно про процедуру авторизации можно почитать [здесь](http://api-docs.diadoc.ru/ru/latest/howto/example_authorization.html).
2. Облачная электронная подпись - это способ функционирования квалифицированной усиленной электронной подписи. Ее можно использовать для подписания СФ.
3.  Отдельной регистрация ЭЦП в Диадоке не требуется. Достаточно один раз зайти в Диадок по сертификату.
4. В API передается уже подписанный контент, процедура подписания происходит локальных машинах.

**Comment by faraon248** [comment]
Андрей, спасибо за четкий и развернутый ответ.
