### ISSUE TITLE
Отсутствие примеров кода в diadocsdk-java

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#193]
Здравствуйте!
Почему для джавы отсутствуют начисто примеры кода? Для сишарпа есть немного:
https://github.com/diadoc/diadocsdk-csharp/tree/master/Samples
Оттуда многое можно транслировать в джаву. Но механизм генерации подписи - нет

**Comment by i82** [comment]
Добрый день. В ближайшее время мы не планируем добавлять примеры кода для java.
