### ISSUE TITLE
В ЛК во входящих первая буква в названии файла отображается Прописной (capitalized)

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#195]
Скорее всего, это не баг sdk, просто я не знаю куда заводить тикеты на ЛК.

Пример сообщения  messageId = 6dc614d8-3864-4bf6-bcab-41c401129a39

Имя, переданное по АПИ sdk и читаемое через него: text_doc2.docx
Имя, отображаемое в ЛК: Text_doc2.docx

Теоретически, если в ящик придут два файла, которые отличаются только тем, прописная или строчная буква у них первая, их невозможно будет различить в ЛК.

![изображение](https://user-images.githubusercontent.com/13780045/86507863-16be8800-bde4-11ea-92ef-fcc50e4c057e.png)

**Comment by NataliaShumikhina** [comment]
Это не баг ни sdk, ни ЛК. В списках мы все документы отображаем с большой буквы. Проблем с этим клиенты не испытывают, потому что вероятность появления двух абсолютно одинаковых названий, которые отличаются только первой буквой, крайне мала. Обычно в названиях используются номера, идентификаторы, даты, по которым можно легко отличить один документ от другого

**Comment by dk2k** [comment]
Такое поведение ЛК не является приемлемым. От пользователей требуются определенные знания о поведении ЛК или соблюдение правил касательно названия файла. Выносите в настройки профиля чекбокс "делать первую букву прописной". Дофолтное значение у галки должно быть false.
