### ISSUE TITLE
SDK не принимает кириллические буквы в названии файла

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#196]
Загружался NonFormalizedDoc
Имя файла тестовый_doc3.docx
Текст ошибки 

{"entityCount":0,"errorReason":"failed to shelf ????????_doc3.docx: org.apache.http.client.HttpResponseException: MessageToPost.NonformalizedDocuments[0]:  имя файла не должно содержать символы < > : “ / \\ | ? * или заканчиваться точкой, пробелом."}

Даже если это ожидаемое поведение (не принимать кириллицу), то текст ошибки неинформативен - перечисленных запрещенных символов приведенное имя файла не содержит.

**Comment by NataliaShumikhina** [comment]
Добрый день! Кириллицу в имени файла мы принимаем, текст запроса должен быть в юникоде. Для этого в заголовке нужно указать Content-Type: application/json,charset=UTF-8
Ошибка информативна и соответствует тому контенту, который мы получили на вход - имя файла из-за неверной кодировки превратилось в вопросительные знаки, которых не должно быть в имени

**Comment by dk2k** [comment]
Почему тикет закрыт? Тикет про sdk, а не прозаголовки. Как с помощью АПИ SDK менять этот заголовок?
