### ISSUE TITLE
Комментарий с кириллическими символами отображается в ЛК вопрос. знаками

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#197]
Комментарий комментарий из нескольких слов. English text.
отображается как 
??????????? ?? ?????????? ????. English text.

![изображение](https://user-images.githubusercontent.com/13780045/86508495-2f7d6c80-bde9-11ea-8dc1-f850781b5ebd.png)

Проблема может быть решена на стороне sdk - надо поменять заголовок
Content-Type: application/json
на
Content-Type: application/json,charset=UTF-8

**Comment by NataliaShumikhina** [comment]
Добрый день! Вы в своем вопросе уже написали ответ - нужно указывать кодировку UTF-8, чтобы кириллические символы нормально отображались
`Content-Type: application/json,charset=UTF-8`

**Comment by dk2k** [comment]
Еще раз. Вопрос в разделе SDK. Как с помощью АПИ SDK управлять содержимым этого заголовка?

**Comment by Dmitriy-Ipatyev** [comment]
Привет, проверьте кодировку, в которой отправляете комментарий. `new String("Комментарий с кириллицей".getBytes(), StandardCharsets.UTF_8))` должно помочь. То же касается и https://github.com/diadoc/diadocsdk-java/issues/196
