### ISSUE TITLE
Как получить подпись контрагента к файлу в виде строки?

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#198]
Есть в тестовой учетке Message с id 6dc614d8-3864-4bf6-bcab-41c401129a39 В его списке entity есть подпись контрагента с entityId db65d780-a587-4296-93ff-e2324c2e7c1d (если нужны еще данные по этому случаю, пишите).
В джава коде я ожидал получить из этой энтити строку с подписью контрагента с помощью вызова:

String content = signatureEntity
        .getContent()
        .getData()
        .toStringUtf8();

Однако, видно, что в data (getData()) строка нулевой длины. Версия sdk 3.2.3.  Это баг? Или есть какой-то другой вариант получить строку с подписью контрагента?

**Comment by Dmitriy-Ipatyev** [comment]
Привет, укажите, пожалуйста, boxId ящика с этим MessageId

**Comment by dk2k** [comment]
Я не очень разбираюсь в терминологии
цепочка начата от ящика 69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru и направлена в e928b1df5d7d41129f0cf33405cce829@diadoc.ru (этот контрагент и подписал файл)

**Comment by Dmitriy-Ipatyev** [comment]
А как вы получаете signatureEntity? С помощью [GetEntityContent](https://api-docs.diadoc.ru/ru/latest/http/GetEntityContent.html)? Тогда контент должен присутствовать. Если разбираете результат [GetMessage](https://api-docs.diadoc.ru/ru/latest/http/GetMessage.html), то для получения контента нужно добавить флаг injectEntityContent.

**Comment by dk2k** [comment]
Спасибо! помогло выставить injectEntityContent=true.
Тикет можно закрывать
