### ISSUE TITLE
Invalid API client id

### ISSUE THREAD

**Issue by WhiteBSco** [diadoc/diadocsdk-java#199]
Есть некий поток который в цикле через каждые 10 минут проверяет наличие новых событий в ящике 62f0a60a-3946-4780-bd42-5fd27ad39e8a.

`BoxEventList boxEventList = apiDiadoc.api.getEventsClient().getNewEvents(apiDiadoc.getBoxId(), apiDiadoc.lastEvent);`

Но после долгого простоя постоянно возникает ошибка:
`Diadoc.Api.exceptions.DiadocSdkException: org.apache.http.client.HttpResponseException: Invalid API client id`

Но стоит ребутнуть приложение, все снова работает, т.е. дело точно не в client id, т.к. он не меняется. 
С чем это может быть связано? или может есть какой то способ переподключения?

**Comment by flosca** [comment]
Привет.
Вообще всегда, когда вы получаете 401, нужно переаутентифицироваться. Токен живёт ~24 часа.

Вот только почему ошибка гласит о невалидном `api client id` вместо токена, я пока не соображу, отвечу позже

**Comment by ThisIsBuddyRIch** [comment]
Добрый день, исправили ошибку с неверным сообщением, релиз -> https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F3.3.3

**Comment by skalolaskovy** [comment]
Сегодня возникла аналогичная проблема - в процессе тестирования ранее успешно проверенных запросов к API  ЭДО Диадок через POSTMAN в ответе приходят либо **ERROR 500**, либо "**Invalid API client id**"
Получение нового client_id ничего не дает... :(
