### ISSUE TITLE
UnsupportedOperationException при вызове api.Authenticate(X509Certificate)

### ISSUE THREAD

**Issue by lshytov** [diadoc/diadocsdk-java#2]
Возникает исключение при попытке авторизации по сертификату: java.lang.UnsupportedOperationException
stackTrace	StackTraceElement[]	#5166(length=0)	
suppressedExceptions	Collections$UnmodifiableRandomAccessList	ObjectVariable 	

Сервер Tomcat 7.0.69, JDK 1.7.0_21, КриптоПРО 1.0.54

Код:
<pre>
import Diadoc.Api.CertificateHelper;
import Diadoc.Api.DiadocApi;
...
api = new DiadocApi("XXX", "https://diadoc-api.kontur.ru");
        X509Certificate currentCert;
        try {
            currentCert = readCert();
            api.Authenticate(currentCert);//java.lang.UnsupportedOperationException
        } catch (Exception ex) {
            LOG.error(ex);
        }
...
private X509Certificate readCert() throws Exception {
        try (InputStream inStream = new FileInputStream("~/kontur.cer")) {
            return CertificateHelper.GetCertificateFromBytes(IOUtils.toByteArray(inStream));
        }
    }
</pre>

**Comment by asvyazin** [comment]
А скопируйте еще полный stacktrace ошибки

**Comment by lshytov** [comment]
Все, что получается вытащить. В логе просто `UnsupportedOperationException`, в дебаге еще видно `suppressedExceptions Collections$UnmodifiableRandomAccessList`

**Comment by asvyazin** [comment]
А если без томката просто консольной java запустить - тоже callstack не выводится?

**Comment by lshytov** [comment]
<pre>
Jul 07, 2016 5:02:57 PM ru.CryptoPro.JCP.tools.Starter check
INFO: Loading JCP 1.0.54 36641
Jul 07, 2016 5:02:57 PM ru.CryptoPro.JCP.tools.Starter check
INFO: JCP loaded.
java.lang.UnsupportedOperationException
	at javax.crypto.CipherSpi.engineGetKeySize(CipherSpi.java:926)
	at javax.crypto.Cipher.passCryptoPermCheck(Cipher.java:1052)
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1010)
	at javax.crypto.Cipher.implInit(Cipher.java:786)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:849)
	at javax.crypto.Cipher.init(Cipher.java:1213)
	at javax.crypto.Cipher.init(Cipher.java:1153)
	at Diadoc.Api.DiadocApi.gostUnwrapKey(DiadocApi.java:239)
	at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:267)
	at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:214)
	at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
</pre>

**Comment by lshytov** [comment]
Проблема решена. Необходимо выполнить процедуру снятия экспортных ограничений с JRE: https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/44/6/snjatie-ehksportnykh-ogrnichenijj

**Comment by asvyazin** [comment]
ok
