### ISSUE TITLE
Работа с контрагентами через API

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#20]
Добрый день.
возник еще ряд вопрос по интеграции:

	1. требования по идентификация получателя: ИНН с документа достаточно или требуется ID 
его ящика? если да. то как через API его можно получить (или каким вообще способом их можно 
получать)?
	2. Для передачи документа в ящик контрагента достаточно ли его уникальной идентификации? 
или пара ЮЛ должна числиться друг у друга в контрагентах? если это не требуется. то как 
реализуется защита от спама? ну. то есть если кто-либо заводит у вас ящик и начинает рассылать 
вообще левым ЮЛ сч/ф, вообще не являясь их контрагентом? понятно. что получатель может не 
принять документ и отменить его. но вообще такая ситуация как то оговаривается?
	3. если у ЮЛ несколько ящиков, на каждый свой логин-пароль (и. соответственно. сессионный 
ключ)?
	4. в Диадоке есть система приглашений- ими регулируется партнерство ЮЛ. возможно ли 
реализовать автоматически через API это? чтобы пользователям не приходилось заходить в Диадок 
для подтверждения партнеров. возможно ли нормальная работа по приему-передаче документов 
без предварительной настройки/загрузки партнеров?

**Comment by atytsky** [comment]
1. Для отправки документов нужны идентификаторы ящика, их можно получить с помощью метода [GetOrganizationsByInnKpp](http://api-docs.diadoc.ru/ru/latest/http/GetOrganizationsByInnKpp.html)
2. Для передачи документа пара ЮЛ может не являться КА в Диадоке. Подробнее в руководстве пользователя [п.8](https://wiki.diadoc.ru/pages/viewpage.action?pageId=1146900).
3. Не обязательно, опять же, авторизуется пользователь, он можем иметь доступ к нескольким ящикам.
4. Да, возможно. Подробнее - [здесь](http://api-docs.diadoc.ru/ru/latest/API_Counteragents.html)

**Comment by faraon248** [comment]
Андрей. спасибо за быстрый ответ.
