### ISSUE TITLE
Как во входящей цепочке отличать файлы с уже проставленной подписью моей организации?

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#205]
Здравствуйте!

Есть цепочка с messageId 6624fbe4-5af2-4063-b350-54bc8099a12d , ее eventId 6624fbe4-5af2-4063-b350-54bc8099a12d

Для меня, как представителя организации "Тестовая организация №2132642" данная цепочка документооборота входящая.
Отправлена с ящика e928b1df5d7d41129f0cf33405cce829@diadoc.ru в ящик 69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru
Сейчас в списке entities_ 13 сущностей, из них 4 - для приаттаченных файлов.
Я подписал в ЛК тестовым сертификатом файл 7test_doc100.txt, это entityId 1033df19-eeda-4bc4-a86b-0e7f606f806a
После подписания мной (как получателем) этого файла в коллекции из 13 сущностей не появилось новых. По каким признакам можно программно понять, что для этого файла уже есть подпись моей организации? Может быть, какой-то признак в сущности с entityId 1033df19-eeda-4bc4-a86b-0e7f606f806a ?

**Comment by ichechulina** [comment]
Добрый день, можете подробнее рассказать, какими методами пользуетесь и с какой целью? Какую информацию требуется получить?

**Comment by dk2k** [comment]
Здравствуйте!
Получаю список событий так:
DiadocMessage_GetApiProtos.BoxEventList boxEventList =
                    diadocApi
                            .getEventsClient()
                            .getNewEvents("69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru", null);

Из них (всего их больше 60, но там еще и исходящие) нахожу входящие для этого ящика, такое пока только одно.
В этом сообщении(событии) 4 файла. Одно из них я сам подписал в ЛК. Но в реальных условиях я не единственный сотрудник компании. Поэтому мне нужно программно проверять, есть ли в сообщении(событии) файлы, которые еще не подписаны организацией, владеющей ящиком "69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru". Тогда я смогу, к примеру, разослать сотрудникам уведомления: есть такое-то сообщение во входящих и в каждом такие-то файлы еще без подписи.

На момент первого получения сообщения из этих 4 файлов в нем было 13 MessageEntity - по 3 на каждый файл и отдельная сущность с CustomData. После того, как я подписал один из файлов, там все равно 13 сущностей. Что-то меняется в сущности подписанного моей организацией входящего файла?

Или есть какой-то другой механизм выделить сообщения/MessageEntity во входящих, которые требую внимания сотрудников организации?

Тут видно, что в ЛК подписан входящий файл:

![signed_file](https://user-images.githubusercontent.com/13780045/87928431-7c21a280-ca8d-11ea-9d55-42192ad82fe7.JPG)

**Comment by aeremina88** [comment]
Добрый день!
Если подпись под входящим документом поставлена, то в ответе метода получите событие установки подписи:
"ParentEntityId": "1033df19-eeda-4bc4-a86b-0e7f606f806a"
"EntityType": "Signature"
"SignerBoxId": "69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru"

**Comment by dk2k** [comment]
Здравствуйте!
Такой подписи в сообщении нет. Как я уже писал, я отслеживал количество сущностей до и после подписания моей организацией одного из файлов. И до и после количество сущностей равно 13. Это баг? Есть только подписи контрагента для каждого файла.

entityId 54fcdfba-ecbc-44da-9746-9bb9e02a39e5
entityType Signature
parentId 1033df19-eeda-4bc4-a86b-0e7f606f806a
signerBoxId e928b1df5d7d41129f0cf33405cce829@diadoc.ru
====================================
entityId 34572316-b32b-4265-8f72-5a11f056fb70
entityType Signature
parentId 4b216c1c-b4aa-4a42-93db-3a70269d9131
signerBoxId e928b1df5d7d41129f0cf33405cce829@diadoc.ru
====================================
entityId 0e3788d1-f5cb-4f2f-9c91-11144785cca9
entityType Signature
parentId 4e6a2624-ba45-4631-82ea-365dcb19f7ee
signerBoxId e928b1df5d7d41129f0cf33405cce829@diadoc.ru
====================================
entityId 832558e4-aa60-4fd2-a5f4-150393c77bcb
entityType Signature
parentId 5c889e42-43fd-4a37-97aa-b36a0a68aec5
signerBoxId e928b1df5d7d41129f0cf33405cce829@diadoc.ru
====================================

Версия сдк 3.2.3.

**Comment by dk2k** [comment]
я не не намеревался капсить дебажный вывод, он отображается крупным шрифтом из-за того, что сайт так распознал разделители в выводе :)

**Comment by aeremina88** [comment]
Попробуйте выполнить метод еще раз. Возможно, событие не успело проиндексироваться.

**Comment by dk2k** [comment]
файл был подписан 17 июля

**Comment by dk2k** [comment]
сущностей по-прежнему 13

**Comment by aeremina88** [comment]
А метод GetMessage для messageId 6624fbe4-5af2-4063-b350-54bc8099a12d возвращает подпись получателя?

**Comment by dk2k** [comment]
Я уже предоставил все данные, перечитывайте тикет

**Comment by ichechulina** [comment]
Вызвали метод GetNewEvents для ящика 69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru, в ответе содержится: 
EventId: "0ec15fa0-8a39-44e8-a2f6-d05dac7119fc"
  Patch {
    MessageId: "6624fbe4-5af2-4063-b350-54bc8099a12d"
    TimestampTicks: 637305977658771999
    Entities {
      EntityType: Signature
      EntityId: "19676aa8-f28a-4f13-9967-324faebbc023"
      ParentEntityId: "1033df19-eeda-4bc4-a86b-0e7f606f806a"
      Content {
        Size: -1
      }
      AttachmentType: Nonformalized
      SignerBoxId: "69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru"
      RawCreationDate: 637305977658771999
      SignerDepartmentId: "00000000-0000-0000-0000-000000000000"
    }
    PatchId: "0ec15fa0-8a39-44e8-a2f6-d05dac7119fc"
    MessageType: Letter
  }
Всего 67, как из них вы выбираете "входящие"?

**Comment by dk2k** [comment]
Входящие цепочки документооборота искал (и продолжаю искать) так:

events
 .stream()
 .filter(event -> event.getMessage().getToBoxId().equals(request.getCurrentBoxId())) ...
					
Механизм поиска подписи в виде отдельного события - совсем не то, что вы писали ранее в этом тикете.
Было бы гораздо логичнее подпись хранить в той же самой цепочке. А так надо делать перекрёстный поиск со сложностью минимум O(n*n).

Вот как работает сейчас моя проверка с учетом вашей информации.
Сначала надо сохранить в отдельный список signatureEntities. Фильтруем все пришедшие в ответе так: тип сущности == Signature && signerBoxId == ящику моей организации.

Потом ищу входящие цепочки документооборота: event.getMessage().getToBoxId().equals(request.getCurrentBoxId())) как и ранее
Для сущности каждого файла из цепочки проверяю, есть в списке signatureEntities такая, у которой: signatureEntity.getParentEntityId() == entityId сущности файла.

Так работает (проверил на цепочке из тикета, подписал еще файлы, они тоже в нашей системе начинают отображаться как подписанные нашей организацией), но выглядит очень громоздко.

**Comment by ichechulina** [comment]
Не очень понял что в конце концов вы пытаетесь сделать, по тому алгоритму что здесь представлен могу дать следующую рекомендацию. 

Структуру signatureEntities можно представить в виде HashMap с ключом в виде parentId. Тогда алгоритмическая сложность снизится с квадратичной до O( n ) так как искать в списке подписей теперь будет за O(1).

**Comment by dk2k** [comment]
То, что я пытаюсь сделать, расписано в теме. Я не понимаю, что тут можно не понять

**Comment by dk2k** [comment]
Итого. Вопросы.
В ЛК я могу просмотреть входящие цепочки документов и по каждому файлу увидеть, нужна ли подпись моей организации (если не поставил еще ее я или другой сотрудник). Как это сделать в java с использованием sdk?

**Comment by i82** [comment]
Для того, чтобы получать события под документов есть два метода GetNewEvents и GetDocflowEvents, в каждом из них есть информация о том, был подписан документ ил нет. Вероятно, что во втором вы найдёте больше информации. Собранный" документ можно получить через GetDocuments. 

Мы не можем подготовить примеры решения кода в рамках обращения на гитхабе. Рекомендую обратиться к вашему менеджеру чтобы получить персональную консультацию по созданию интеграции.

**Comment by dk2k** [comment]
Очень странное заявление. После обращения к моему менеджеру вы выпустите отдельную кастомную версию sdk?

**Comment by NataliaShumikhina** [comment]
Нет, кастомную версию sdk  мы не сделаем, но вы сможете получить персональную консультацию по настройке интеграционного решения с учетом ваших потребностей и особенностей интеграции
