### ISSUE TITLE
Формирование ссылки на документ для веб версии площадки Диадок

### ISSUE THREAD

**Issue by MaximKuznetsov17** [diadoc/diadocsdk-java#207]
**Здравствуйте!**

Могу ли я каким-то образом получить ссылку на документ для просмотра и редактирования его на сайте Диадок при работе с библиотекой diadocsdk-java? 
Возможно есть какие-то методы, позволяющие сформировать ссылку? Если такой возможности сейчас нет, то планируется ли она в будущих релизах?

Заранее спасибо!

**Comment by aeremina88** [comment]
добрый день!
Отдельного метода нет. Добавлять пока не планировали.
Сейчас ссылка имеет вид:
https://diadoc.kontur.ru/{boxId}/Document/Show?letterId={letterId}&documentId={documentId}

**Comment by MaximKuznetsov17** [comment]
Добрый день!
Спасибо!
