### ISSUE TITLE
SDK присылает битый архив с документооборотом

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#210]
Размер массива байтов в отладочном логгировании:

2020-07-29 21:13:22 DEBUG  Controller:1239 - Size 8207063 bytes

Размер файла сброшенного на диск:
![изображение](https://user-images.githubusercontent.com/13780045/88837842-5c068780-d1e1-11ea-8d4e-b3c3997e0662.png)

Т.е. размеры совпадают и при сбрасывании ничего не потерялось и не дописалось.

В архиве можно просмотреть список файлов, но при распаковке ошибка:
![изображение](https://user-images.githubusercontent.com/13780045/88837948-82c4be00-d1e1-11ea-9575-b7555c5cc196.png)

файл выкладываю в облако:  https://drive.google.com/file/d/1yPfPk8Six5mSoNh7eTBfyCCd4-9NF9is/view?usp=sharing

Параметры запроса:

"boxId":"69e1d7722e5b47b8b3cfa1d58e902907@diadoc.ru",
"messageId":"136663de-ee59-4697-b8cb-2e6761eb200c",
"documentId":"f7479646-c3c8-4d39-9a28-d6c0327f94a6",
"fullDocflow": true

**Comment by alogicman** [comment]
Какую версию sdk используете?

**Comment by dk2k** [comment]
Версия sdk 3.3.3

Файл сбрасывается в файловую систему так:
DocumentZipProtos.DocumentZipGenerationResult archiveResult = result.getDocumentZip();
String filename = archiveResult.getZipFileNameOnShelf();
byte[] archiveBytes = diadocApi
                        .getShelfClient()
                        .shelfDownload(filename);
DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd_MM_yyyy_hh_mm_a");
                File out = new File("c://doc" + ldt.format(dtf) + ".zip");
                try (PrintWriter writer = new PrintWriter(out);) {
                    writer.print(new String(archiveBytes));
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }

**Comment by DMokhnatkin** [comment]
Тот архив который вы приложили отличается от того что вернул Диадок (да, размер совпадает но хэш сумма нет). Приведенный вами способ записи в файловую систему у меня вызывает подозрения. Попробуйте поискать другой способ, например https://stackoverflow.com/questions/1769776/how-can-i-write-a-byte-array-to-a-file-in-java/1769838

**Comment by dk2k** [comment]
Ваш совет помог, спасибо. Тикет можно закрывать.
Сбрасывать файл надо так:
                File out = new File("c://doc.zip");
                FileOutputStream output = null;
                try {
                    output = new FileOutputStream(out);
                    IOUtils.write(archiveBytes, output);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
