### ISSUE TITLE
Список библиотек для явы 5

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#22]
Подскажите список библиотек (с конкретными версиями jar файлов),
чтобы работал диадок на яве 5.

**Comment by asvyazin** [comment]
Непосредственные зависимости перечислены в maven-овском файле pom.xml (кроме Crypto Pro, которая отсутствует в репозиториях maven). У этих зависимостей есть, в свою очередь, тоже зависимости. Полный список всех необходимых библиотек никто никогда не составлял, да это и не нужно, потому что maven при сборке все, что нужно, скачивает автоматически.
