### ISSUE TITLE
Загрузка событий GetNewEvents

### ISSUE THREAD

**Issue by eremenkoKS** [diadoc/diadocsdk-java#229]
Добрый день мы используем интеграции с Диадок по средствам API. Вычитываем новые поступающие события по средствам метода [GetNewEvents](https://api-docs.diadoc.ru/ru/latest/http/GetNewEvents.html), записываем их в БД с проверкой на уникальность ящика + id события, затем в отдельной транзакции обрабатываем полученные данные. 

05.04.2021 мы получили события с id который уже присутствовал в нашей БД для данного ящика. За почти год работы это первый случай.

Скажите существует ли возможность получить событие с id которое фигурировало в ящике ранее, если в аргументы функции передано более позднее id?

**Comment by alogicman** [comment]
Подскажите, пожалуйста, в каком ящике произшла эта ситуация?

**Comment by eremenkoKS** [comment]
05.05 история повторилась.

Ящик `a54db667-56af-42ae-a08b-0c6f14b709b7`
```
2021-05-05 14:07:52,139 [P=832300:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка 72fdc269-57f4-4e6e-a1ab-097fa2d7a14d события
... ... ... ... ...
2021-05-05 14:07:53,985 [P=832300:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка 72fdc269-57f4-4e6e-a1ab-097fa2d7a14d события
```
Ящик `a2d176cb-1ab7-4050-92b6-1d4f364dec46`
```
2021-05-05 16:07:24,557 [P=32244:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка 7f52c892-a159-46b2-898c-45f3d3bae719 события
... ... ... ... ...
2021-05-05 16:07:25,916 [P=32244:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка 7f52c892-a159-46b2-898c-45f3d3bae719 события
```
Ящик 011290ba-5c02-45cb-b38f-1c8e2d018538
```
2021-05-05 19:07:47,490 [P=831284:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка ee4c6774-71fb-4534-806b-15b557e41e50 события
... ... ... ... ...
2021-05-05 19:07:48,779 [P=831284:O=0:CT] DEBUG r.t.u.r.diadoc.impl.EventProcessor - Обработка ee4c6774-71fb-4534-806b-15b557e41e50 события
```

Время MSK

Собственно незамысловатый код
``` java
    @Override
    public void process(String boxId) throws DiadocSdkException {
        log.info("Обработка событий для ящика {}", boxId);
        String lastEvent = state.getState(boxId); //<- Получение последнего события
        log.info("Начальное событие {}", lastEvent);
        BoxEventList events;
        do {
            events = eventsClient.getNewEvents(boxId, lastEvent);
            log.info("Получено {} событий", events.getEventsCount());
            for (BoxEvent boxEvent : events.getEventsList()) {
                lastEvent = boxEvent.getEventId();
                log.debug("Обработка {} события", lastEvent));
                if (processEvent(boxId, boxEvent)) {
                    state.saveState(boxId, lastEvent); //<- Запись каждого события
                } else {
                    return;
                }
            }
        } while (!TotalCountType.Equal.equals(events.getTotalCountType())
                || events.getTotalCount() > events.getEventsCount());
    }

```

**Comment by NataliaShumikhina** [comment]
Добрый день! К сожалению, такая ситуация возможна, когда возникает несколько событий с одинаковым идентификаторам. Это возможно в сценарии, когда исходящие неотправленные документы из одного письма подписываются разными патчами в один момент времени. Эти события полностью идентичные, поэтому достаточно обработать только одно из них. Поэтому можно порекомендовать вам пропускать такие дубли событий

**Comment by alogicman** [comment]
1. В случае afterEventId по дублирующемуся идентификатору вернутся следующие события
2. Не гарантируется, что события идут сразу друг за другом
