### ISSUE TITLE
Как получить из УПД Дату приемки результатов работ

### ISSUE THREAD

**Issue by RayderXEE** [diadoc/diadocsdk-java#235]
Добрый день. В рамках доработки нашего Java API интеграционного решения мы столкнулись с проблемой. Как используя DiadocSDK API получить из УПД **Дату приемки результатов работ**, после того как документ был подписан у заказчика? Нам необходима эта информация в нашей базе данных.

**Comment by i-am-bad-bull** [comment]
Дату приемки (AcceptanceDate) можно вытащить из титула покупателя. Для этого используйте метод парсинга [ParseTitleXml](https://diadoc-sdk.readthedocs.io/ru/latest/http/ParseTitleXml.html).
