### ISSUE TITLE
Статус отправленного документа

### ISSUE THREAD

**Issue by breewee** [diadoc/diadocsdk-java#236]
Здравствуйте! Подскажите, как после отправки неформализованного документа контрагенту, можно отследить статус его изменения (ожидает подписи контрагента/подписан/документооборот завершен). После отправки сохраняю messageId, по идее мне надо как то получить messageId этого документа в ящике контрагента, подскажите как это сделать

**Comment by breewee** [comment]
Из доступных мне данных: fromBoxId, toBoxId и Message postedMessage, возвращенный метотдом api.getMessageClient().postMessage(messageBuilder.build())

**Comment by aeremina88** [comment]
Добрый день!
messageId одинаковый со стороны отправителя и со стороны получателя.
Кроме messageId вам нужно сохранять documentId, т.к. в общем случаем в сообщении может быть несколько документов.
Для получения статуса можно использовать GetMessage, GetDocument или вычитывать ленту событий вашего ящика GetNewEvents или GetDocflowEvents_V3.

**Comment by aeremina88** [comment]
Добрый день!
А каким методом выполняете подписание и отправку документа?
Можете указать boxid, messageId и documentId?

**Comment by breewee** [comment]
> Добрый день!
> А каким методом выполняете подписание и отправку документа?

Как написал выше:
"Выбор контрагента, подписание и отправку документа к нему коллеги делают из веб-морды"
из кода только создаю черновик, и запоминаю messageId

**Comment by NataliaShumikhina** [comment]
Добрый день! Алгоритм, который вы используете, верный. Подскажите, пожалуйста, boxid, messageid и entityid документа, для которого после отправки возвращается статус "Требуется подписать и отправить"

**Comment by breewee** [comment]
Пример: 
messageId = aad39dd9-2d4f-4592-9961-3a9033bb1251
fromboxId = db80e54b4cfd446fb72a1a9ee3c8ce0b@diadoc.ru
достаю Message через метод: DiadocApi.getMessageClient().getMessage(fromBoxId, messageId)

далее достаю статус энтити:
entityId = 42f12aed-2d08-4c9e-844b-0b0eb5dc6ab0
message.getEntities(0).getDocumentInfo().getDocflowStatus()

полученное значение: "Требуется подписать и отправить"

Хотя, как мы можем видеть на скриншоте: документ уже подписан и отправлен.

![image](https://user-images.githubusercontent.com/61110637/133393389-843b8326-3f8e-4c80-8c2a-310188d87f7d.png)

**Comment by i-am-bad-bull** [comment]
"MessageId":  "aad39dd9-2d4f-4592-9961-3a9033bb1251" принадлежит черновику, поэтому вам возвращается его статус "Требуется подписать и отправить".
Также в ответе на выполнение метода V5/GetMessage пришла информация о том, что это черновик ("MessageType": "Draft").
Чтобы просмотреть информацию по отправленному из черновика документу, указывайте в запросе идентификатор этого документа. В вашем случае "MessageId": "6ac719d3-b4b1-4186-8fc5-0c853dc042d1".

**Comment by breewee** [comment]
а если у меня есть данные только о черновике, которые я получаю при его создании, как мне исходя из messageId черновика получить messageId уже отправленного из него документа?

**Comment by i-am-bad-bull** [comment]
В ответе на V5/GetMessage по черновику ("MessageId": "aad39dd9-2d4f-4592-9961-3a9033bb1251") будут содержаться идентификаторы сформированных на основании этого черновика документов:
_"DraftIsTransformedToMessageIdList": [ "6ac719d3-b4b1-4186-8fc5-0c853dc042d1"]_

**Comment by breewee** [comment]
получилось, спасибо

**Comment by breewee** [comment]
считываю статусы вот так: если есть созданные по черновику доки то билжу их статусы, в противном случае - статус черновика:

StringBuilder docStatusBuilder = new StringBuilder();
Message sourceMsg = api.getMessageClient().getMessage(fromBoxId, messageId);
ProtocolStringList msgIds = sourceMsg.getDraftIsTransformedToMessageIdListList();
			if (!msgIds.isEmpty()) {
				for (String msgId : msgIds) {
					docStatusBuilder.append(api.getMessageClient().getMessage(fromBoxId, msgId)
							.getEntities(0).getDocumentInfo().getDocflowStatus()
							.getPrimaryStatus().getStatusText()).append(", ");
				}
				responseMap.put("documentStatus",
						docStatusBuilder.substring(0, docStatusBuilder.length() - 2));
			} else {
				responseMap.put("documentStatus",
						sourceMsg.getEntities(0).getDocumentInfo().getDocflowStatus()
								.getPrimaryStatus().getStatusText());
			}

**Comment by i-am-bad-bull** [comment]
Кажется, что нет необходимости вычитывать статус черновика, тк он в любом случае будет WaitingForSenderSignature. Даже если на его основании уже создан документ или черновик был удалён.
Достаточно посмотреть, был ли из него создан документ/документы и если да, вычитать уже их статус.
