### ISSUE TITLE
Вариации действий контрагента при получении счф

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#24]
Добрый день.
подскажите по следующему вопросу:
после того, как автор подписал документ и отправил его своему контрагенту, по всем описанным схемам можно сделать вывод, что у получателя нет никаких вариаций действий- более того, принятие документа и подписание/отправка всех квитанций  (уведомлений) происходит без его непосредственного участия. то есть схема работы жестко зашита? а если получателя не устраивает полученный документ, он должен после подписания/отправки всех квитанций (уведомлений) может запустить новый функционал- запрос уточнения? то есть отправленную в наш адрес сч/ф мы получаем и принимаем у себя в любом случае. а если с ней проблемы и/или мы не хотим принимать вообще ее- необходимо запрашивать уточнение? нет возможности в момент получения оценить ее. и если необходимо, сразу отменить?

**Comment by faraon248** [comment]
просьба также подсказать- есть ли более быстры способ задавать вопросы по интеграции? или только тут?

**Comment by atytsky** [comment]
Регламент обмена СФ описан в приказе [№174](https://normativ.kontur.ru/document?moduleId=1&documentId=268278). Он же определяет схему работы.

При получении СФ, вы как получатель должны сформировать 3 извещения о получении электронного документа - нам сам СФ, и на два подтверждения от оператора. Если после получение, у вас есть замечания по СФ, вы должны отправить запрос на уточнение. 

Вы можете конечно не проделывать все эти действия, но тогда СФ не будет считаться как полученная и отправитель не узнает, что вас не устраивает в документе.
Поэтому лучше придерживаться схемы работы, которая описана в приказе [№174](https://normativ.kontur.ru/document?moduleId=1&documentId=268278).

Все способы задать вопрос, описаны [здесь](http://www.diadoc.ru/integrations/api). Вы можете задавать вопросы на почту diadoc@skbkontur.ru. Но я не думаю, что этот вариант будет сильно быстрее.
