### ISSUE TITLE
Как через API выполнить Отказ в подписании и процесс Аннулирования?

### ISSUE THREAD

**Issue by savinov-anton-v** [diadoc/diadocsdk-java#240]
При работе через Личный кабинет в результате **Отказа в подписании** неявно формируется протокол об отказе **DP_UVUTOCH_...** и подписываем именно его. Если потом скачать документооборот целиком, то в архиве будет XML-файл протокола и подпись к нему.
![image](https://user-images.githubusercontent.com/53437138/141748094-b83748d2-ef6a-4469-81e5-c95fb8891fa1.png)

В описании https://api-docs.diadoc.ru/ru/latest/proto/MessagePatchToPost.html отказ предлагается выполнять через список _XmlSignatureRejections_ структур _XmlSignatureRejectionAttachment_.
`message XmlSignatureRejectionAttachment {
    required string ParentEntityId = 1;
    required SignedContent SignedContent = 2;
    repeated string Labels = 3;
}`

Что есть что в этом случае для **Отказа**:
1. ParentEntityId - это ID первоначального документа или протокола об отказе?
2. SignedContent - Signature в нём является подписью протокола от отказе? В Content/NameOnShelf передавать протокол об отказе/ссылку на него?
3. Касается обоих пунктов выше - как предварительно создать протокола об отказе и связать с первоначальным документом?

С **Аннулированием** через Личный кабинет в начале аналогично - тот, кто отправляет **Запрос на Аннулирование** неявно формирует соглашение об аннулировании **DP_PRANNUL_...** и подписывает его. XML-файл соглашения и подпись к нему также можно будет найти в архиве документооборота в папке _Аннулирование_.
В описании https://api-docs.diadoc.ru/ru/latest/proto/MessagePatchToPost.html аннулирование предлагается выполнять также через список _XmlSignatureRejections_ структур _XmlSignatureRejectionAttachment_.

Что есть что в этом случае для **Запроса на Аннулирование**:
1. ParentEntityId - это ID первоначального документа или соглашения об аннулировании?
2. SignedContent - Signature в нём является подписью соглашения об аннулировании? В Content/NameOnShelf передавать соглашение об аннулировании/ссылку на него?
3. Касается обоих пунктов выше - как предварительно создать соглашение об аннулировании и связать с первоначальным документом?

Если правильно понимаю, то при **подтверждении Аннулирования контрагентом** надо также использовать _XmlSignatureRejectionAttachment_. Верно ли, что:
1. ParentEntityId - это ID соглашения об аннулировании?
2. SignedContent - Signature в нём является подписью соглашения об аннулировании контрагентом? В Content/NameOnShelf что передавать?

И последнее - как выполнить **Отказ в Аннулировании**? Ведь там нужно сформировать протокол об отказе на соглашение об аннулировании. Что в этом случае передавать в _XmlSignatureRejectionAttachment_?

**Comment by i-am-bad-bull** [comment]
**_Что касается отказа в подписи:_**
В ParentEntityId прописывается идентификатор документа, к которому отправляется дополнение (патч). В данном случае патчем будет отказ.
Signature в SignedContent является подписью файла отказа.
Файл отказа формируется с помощью метода [GenerateSignatureRejectionXml](https://api-docs.diadoc.ru/ru/latest/http/GenerateSignatureRejectionXml.html).

**_Предложение об аннулировании:_**
ParentEntityId также является идентификатором документа, на который отправляется запрос.
Signature в SignedContent является подписью файла предложения об аннулировании.
Файл предложения об аннулировании формируется с помощью метода [GenerateRevocationRequestXml](https://api-docs.diadoc.ru/ru/latest/http/GenerateRevocationRequestXml.html).

**_Подтверждение аннулирования:_**
Ответная подпись под запросом на аннулировании заполняется в [Signatures](https://api-docs.diadoc.ru/ru/latest/proto/MessagePatchToPost.html#:~:text=%D0%B0%20%D1%82%D0%B0%D0%BA%D0%B6%D0%B5%20%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BD%D1%8B%D0%BC%D0%B8%20%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%8F%D0%BC%D0%B8%20%D0%BF%D0%BE%D0%B4%20%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%BC%20%D0%BD%D0%B0%20%D0%B0%D0%BD%D0%BD%D1%83%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0.).

**_Отказ в аннулировании:_**
Да, все верно, отказ передается в рамках [XmlSignatureRejectionAttachment](https://api-docs.diadoc.ru/ru/latest/proto/MessagePatchToPost.html#:~:text=%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B9%20%D0%BF%D0%BE%20%D0%BE%D1%82%D0%BA%D0%B0%D0%B7%D1%83%20%D0%BE%D1%82%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9%20%D0%BE%D0%B1%20%D0%B0%D0%BD%D0%BD%D1%83%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8).

**Comment by savinov-anton-v** [comment]
Спасибо
