### ISSUE TITLE
Несоответствие parentEntityId в event.patch.entities[...] и в message.entities[...]

### ISSUE THREAD

**Issue by archimed7592** [diadoc/diadocsdk-java#242]
Здравствуйте.

Забираем новые события `api.getEventsClient().getNewEvents(boxId, lastEventId)`.

Внутри смотрим на `event.getPatch().getEntitiesList()` и видим для некоторых entity с типом Signature что ParentEntityId отличается от ParentEntityId для той же Signature, которую мы видим при запросе `api.getMessageClient().getMessage(boxId, messageId)`.

Можете пояснить, как нам такие ситуации интерпретировать? Или это баг и вы поправите на серверной стороне?

Во вложении скриншот:
![Screenshot_13](https://user-images.githubusercontent.com/35864862/145030774-9224067b-5acf-4b85-9159-0a5053045c6c.png)

```
boxId: 6f2907d40926466caf34859ec5ff7fa5@diadoc.ru
messageId: b82acce3-3043-4ef5-beab-0e108454f929
eventId: 280cb94b-757b-4f50-bf80-96b123667982
entityId (signature): 5adbe4c3-8a2f-47f4-9381-9d6e345262a0
parentEntityId (внутри event):   f758548d-1ec0-42a4-8870-22450577ee5b
parentEntityId (внутри message): 624dbf59-cb0f-453c-aa70-72b899049553
```

**Comment by i-am-bad-bull** [comment]
Добрый день!
При выполнении этих методов идентификаторы одной и той же сущности действительно могут отличаться.
Метод GetNewEvents предназначен для вычитки всех событий в ящике, когда GetMessage возвращает информацию по конкретному сообщению.
В первом случае возвращается больше информации, туда включаются и, например, проверки подписи.
