### ISSUE TITLE
Как автоматически определять документы с статусом "Ошибка в подписи"

### ISSUE THREAD

**Issue by Sergerg** [diadoc/diadocsdk-java#244]
Добрый день.
У пользователей нашего интеграционного решения стала возникать ошибка в подписи, которую мы не обрабатываем.
Воспроизвели данную ошибку на тесте и попытались отловить события связанные с ней. Однако выяснилось, что при данной ошибке, события, похоже, не генерируются. 
На данный момент имеем возможность определить ошибку только перепроверяя статус документа, но для этого, как минимум, придётся перебирать все документы.
Имеется ли другая возможность через SDK обрабатывать статусы "Ошибка в подписи" без перебора документов?

**Comment by ilzag** [comment]
Добрый день!
Есть несколько способов, как отслеживать ошибки в подписи.
- Если воспользоваться методом [GetNewEvents](https://developer.kontur.ru/Docs/diadoc-api/http/GetNewEvents.html) для вычитки ленты событий, то в структуре Events, в подструктуре Entities будет сообщение об ошибке ("EntityType": "Attachment", "AttachmentType": "DeliveryFailureNotification", в подструктуре "Content" - текст сообщения об ошибке в Base64).
- Если воспользоваться методом [GetDocflowEvents](https://developer.kontur.ru/Docs/diadoc-api/http/GetDocflowEvents_V3.html), то для событий с ошибкой в подписи в структуре RecipientResponse будет "ResponseStatus": "InvalidRecipientSignature" для ошибок в подписи получателя и "SenderSignatureStatus": "SenderSignatureCheckedAndInvalid" для ошибки в подписи отправителя в структуре SenderTitle.

**Comment by Sergerg** [comment]
Спасибо!
