### ISSUE TITLE
Ошибка при попытке авторизации  /V3/Authenticate

### ISSUE THREAD

**Issue by Bishamon18186** [diadoc/diadocsdk-java#248]
Добрый день. 
При попытке авторизации методом **POST /V3/Authenticate** (https://api-docs.diadoc.ru/ru/latest/http/Authenticate.html) возникает ошибка _"Caused by: java.lang.RuntimeException: null
 at Diadoc.Api.DiadocCredentials.getPassword(DiadocCredentials.java:54)_"
Такая ошибка возникает для сертификатов от 2022 года, для сертификатов от 2021 метод отрабатывает без ошибок.
В чем может быть проблема?

**Comment by ilzag** [comment]
Добрый день.
Пришлите, пожалуйста, кусок кода, вызывающий ошибку.

**Comment by alskaa** [comment]
Здравствуйте!

вызываем httpClient.execute(httpPost);

где httpPost - HttpPost вида 

POST /V3/Authenticate?type=certificate HTTP/1.1 
[Content-Length: 2556, 
Host: diadoc-api.kontur.ru, 
Connection: Keep-Alive, 
User-Agent: Apache-HttpClient/4.5.13 (Java/1.8.0_292), 
Accept-Encoding: gzip,deflate, 
Authorization: DiadocAuth ddauth_api_client_id=наш api_client_id]

в теле запроса сертификат
