### ISSUE TITLE
необходимость использования библиотек JCP

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#25]
добрый день.
прошу прояснить следующий вопрос:
сейчас занимаемся интеграцией нашего облачного сервиса с Диадок через Java API.
Реализация примерно следующая:
У пользователя локально установлен CryptoPro plugin в браузере и CSP с токенами на компьютере.
из своего облака мы выгружаем файл в локальное хранилище. обращается к плагину и подписываем документ. обратно загружаем  в облако уже подписанный документ.
после этого, авторизовавшись в Диадоке, получаем сессионный ключ. 
используя этот ключ. посылаем в Диадок подписанные документы. это в теории.
на практике столкнулись с проблемой- работа модуля. построенного на методах, описанных в вашем АПИ. требует наличия библиотек JСP- то есть установленного у нас на сервере JSP модуля от КриптоПро- без этого нет возможности и собрать модуль. возникает вопрос- для чего требуется библиотека JСP, если работа с криптографией осуществляется локально у пользователя?

Возможно ли работать напрямую через HTTP-API без JCP?

**Comment by asvyazin** [comment]
К сожалению через наш SDK в данный момент это невозможно, модуль работы с криптографией интегрирован в Java SDK, к тому же он еще используется, например, для авторизации по сертификату, а не только для формирования ЭЦП. Отделить его возможно, но надо приложить определенные усилия, к тому же это довольно сложно сделать, не нарушив обратной совместимости с существующим кодом, а пока у нас нет намерений менять существующий интерфейс.

Насколько критична для вас эта проблема?

**Comment by lolpany** [comment]
Я не сотрудник Диадока.
JCP используется только в методе Authorize по сертификату. Его можно закомментировать, и все методы которые он использует, и импорты ставшие ненужными тоже. Потом побилдить без JCP.
Это на текущий момент.
А можно прямо через HTTP конечно.
