### ISSUE TITLE
Статус «Подписан с разногласиями»

### ISSUE THREAD

**Issue by vikosiV** [diadoc/diadocsdk-java#251]
Где указывается (какое свойство использовать) текст замечаний в случае подписания документа с разногласиями как для формализованных (это в титуле?) и для неформализованных документов?
Для титула есть в ContentOperCode только атрибут TotalCode, но атрибута для замечания нет.

**Comment by ilzag** [comment]
Добрый день!
В инфомодели титула покупателя для 820 приказа ФНС комментарий можно указать в `OperationContent`. В xml это атрибут `СодОпер` элемента `СвПрин`.
Подписать с разногласиями неформализованный документ нельзя.
