### ISSUE TITLE
Есть ли в API Диадок метод для возврата некорректного документа?

### ISSUE THREAD

**Issue by lteny** [diadoc/diadocsdk-java#256]
Добрый день.
Прошу оказать консультацию.
После получения из СЭДО «Контур.Диадок» документов от контрагентов на стороне нашей системы планируется проводить валидацию документов, с целью проверки корректности и полноты полученных данных. При валидации могут быть выявлены несоответствия (например, отсутствие обязательного атрибута), которые препятствуют дальнейшей обработке документа в нашей системе. 
В связи с чем возникает вопрос: предусмотрен ли в API Диадок метод для возврата данного документа в СЭДО «Контур.Диадок», который будет обновлять статус документа и информировать контрагента, отправившего данный документ о наличии несоответствий.

**Comment by lteny** [comment]
Добрый день. Прошу ответить на вопрос.

**Comment by ilzag** [comment]
Добрый день!
Если в документе обнаружены ошибки, то с помощью метода [PostMessagePatch](https://developer.kontur.ru/Docs/diadoc-api/http/PostMessagePatch.html) возможно (в зависимости от статуса документа, типа документа):
1. Отправить отказ в подписи (`XmlSignatureRejectionAttachment`), указав комментарий в файле отказа. Возможно получателем, если документооборот по документу ещё не завершён и тип документа предполагает подпись получателя.
2. Отправить запрос на аннулирование (`RevocationRequestAttachment`), указав причину в файле предложения об аннулировании. Возможно, если документооборот по документу завершён. Получатель предложения может отказать в аннулировании.
3. Отправить запрос на корректировку (`CorrectionRequestAttachment`), указав причину запроса в файле уведомления об уточнении. Используется в документообороте СФ/ИСФ/КСФ/ИКСФ, что предусмотрено порядком обмена счетов-фактур.
