### ISSUE TITLE
Признак завершенного документооборота

### ISSUE THREAD

**Issue by olgapopova78** [diadoc/diadocsdk-java#257]
Возвращает ли запрос /V3/GetDocflowEvents какой-либо признак, что по документу больше нет доступных действий, т.е. его нельзя подписать/отказать/аннулировать?

Или каким образом можно это определить (комбинация признаков/другой запрос API/...)?

**Comment by ilzag** [comment]
Добрый день!
Ориентируйтесь на структуру [DocflowV3](https://developer.kontur.ru/Docs/diadoc-api/proto/DocflowV3.html). Учитывайте комбинации статусов различных сущностей, относящихся к документу. Например, можно считать, что документооборот завершён, если: 
1. [SenderTitle](https://developer.kontur.ru/Docs/diadoc-api/proto/SenderTitleDocflow.html).IsFinished == true и SenderTitle.[SenderSignatureStatus](https://developer.kontur.ru/Docs/diadoc-api/proto/SenderSignatureStatus.html) == SenderSignatureCheckedAndValid.
2. [Confirmation](http://api-docs.diadoc.ru/ru/latest/proto/ConfirmationDocflow.html).IsFinished == true или отсутствует.
3. [RecipientReceipt](http://api-docs.diadoc.ru/ru/latest/proto/ReceiptDocflowV3.html).IsFinished == true или отсутствует.
4. [SenderReceipt](http://api-docs.diadoc.ru/ru/latest/proto/ReceiptDocflowV3.html).IsFinished == true или отсутствует.
5. [RecipientResponse](https://api-docs.diadoc.ru/ru/latest/proto/ParticipantResponseDocflow.html) отсутствует или RecipientResponse.IsFinished == true и RecipientResponse.RecipientResponseStatus == WithRecipientSignature или RecipientResponse.RecipientResponseStatus == WithRecipientPartiallySignature.
6. [ProxyResponse](https://api-docs.diadoc.ru/ru/latest/proto/ParticipantResponseDocflow.html) отсутствует или ProxyResponse.IsFinished == true и ProxyResponse.ProxySignatureStatus == WithProxySignature.
7. [Revocation](http://api-docs.diadoc.ru/ru/latest/proto/RevocationDocflowV3.html) отсутствует или Revocation.IsFinished == true и Revocation.RevocationStatus == RevocationRejected.
8. [AmendmentRequest](http://api-docs.diadoc.ru/ru/latest/proto/AmendmentRequestDocflow.html) отсутствует или IsFinished = true
