### ISSUE TITLE
Настройка JCP для Оракла

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#26]
Файлы JCP загрузили в базу Оракл (11.2) использую loadjava.
(Без файлов JCP не грузится diadocsdk).
Как теперь настроить JCP?

**Comment by asvyazin** [comment]
Не совсем понял вопрос. Если все работает, то настраивать ничего не нужно, если что-то не работает, то напишите, что именно.

**Comment by Insapov** [comment]
Не работает. Не находит JCP. И не понятно как настраивать для оракловой виртуальной машины. 
Для явы на операционной системе есть controlpane . А как настраивать для внутриоракловой виртуальной машины?

**Comment by asvyazin** [comment]
Через ControlPane можно только лицензионный ключ JCP задать и путь к хранилищу приватных ключей сертификатов (путь можно и не задавать, если устраивает дефолтный), но это не поможет найти JCP, если виртуальная машина его не видит, в этом случае и сама ControlPane не запустится.

Напишите сообщение об ошибке и при каком действии она появляется, и лучше всего - весь стэк вызовов.
