### ISSUE TITLE
Вопрос по API Диадока

### ISSUE THREAD

**Issue by TatyanaDiadoc** [diadoc/diadocsdk-java#260]
Добрый день.
Прошу вас сориентировать по вопросу API Диадока. 
Цитата из API : "Необязательно вызывать метод Authenticate перед каждым обращением к методам API Диадока- авторизованные токены можно кэшировать. Мы рекомендуем сохранить и использовать полученный токен в течение всего сеанса работы."
Но ничего не указано сколько по времени составляет сеанс работы. Сколько длится "жизнь токена"? Насколько нормально/плохо получать токен при каждом обращении?

**Comment by ilzag** [comment]
Добрый день!
Жизнь токена составляет примерно сутки. Никто не запрещает вам запрашивать его при каждом запросе, но это естественным образом повышает нагрузку, поэтому мы рекомендуем токен кешировать.
