### ISSUE TITLE
Заполнение Refusals в TemplatePatchToPost

### ISSUE THREAD

**Issue by olgapopova78** [diadoc/diadocsdk-java#268]
Добрый день.

Делаем отзыв шаблона документа через API PostTemplatePatch.

Нужно ли заполнять блоки Refusals, если по шаблону еще не были присланы документы?
Правильно ли я понимаю, что эти блоки заполняются только для отклонения/отзыва именно документов, созданных по шаблону?

**Comment by ilzag** [comment]
Добрый день!
Refusals заполняется, если из данного шаблона более не требуется создавать документы. Если вы отклоните/отзовёте шаблон, создать документ из него более будет нельзя, а также невозможно будет подписать и отправить, однако уже отправленные документы затронуты не будут.

Отвечая на ваш вопрос - если вы ещё ожидаете, что контрагент из шаблона создаст и отправит вам документ, не заполняйте структуру Refusals
