### ISSUE TITLE
Docflow API

### ISSUE THREAD

**Issue by digoncharenko** [diadoc/diadocsdk-java#27]
добрый день. 
в данный момент в последней версии SDK отсутствует JAVA реализации для Docflow API. когда можно ожидать портирования Docflow API на JAVA?

**Comment by atytsky** [comment]
Сейчас Java SDK действительно не поддерживает Doclow API, мы планируем добавить поддержку до конца сентября.

**Comment by asvyazin** [comment]
Метод SearchDocflows добавлен, в версии 1.36.4 он уже есть. Остальные методы будут добавляться по мере необходимости, если еще какие-то конкретные методы нужны прямо сейчас, то надо будет переоткрыть тикет и написать какие методы требуются.

**Comment by atytsky** [comment]
#29
