### ISSUE TITLE
Аутентификация не происходит на ironport

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#3]
Видимо нужно где-то в программе указывать настройки прокси. Где?
Если попробовать перед этим Explorer-ом ткнуться куда-нибудь в инет, он авторизуется на прокси и может пропустить пакет с этого же ip-шника, но это не всегда работает.

**Comment by asvyazin** [comment]
Работа с прокси в Sdk для Java пока не поддерживается и пока не планировалось делать поддержку. Но если вдруг сможете реализовать самостоятельно, то присылайте pull request.
