### ISSUE TITLE
Настройка тестового окружения

### ISSUE THREAD

**Issue by faraon248** [diadoc/diadocsdk-java#31]
Добрый день.
Прошу помочь с проблемой:
в данный момент занимаемся интеграцией с Диадоком через JAVA API.
для проверки работы создали на вашем тестовом сервере личный кабинет.
но выпущенный через сервис Крипто-про тестовый сертификат невозможно прикрепить к данному кабинету.
возможно ли заказать тестовые сертификаты на 2 юридических лица? 
локальные- т.к. вариант работы с облачной подписью пока не прорабатывали.

**Comment by atytsky** [comment]
[Здесь](http://www.diadoc.ru/integrations/api) можно оставить заявку на получение тестового КЭП. Такой вариант подойдет вам?
