### ISSUE TITLE
Прикрепление подписи к документу

### ISSUE THREAD

**Issue by vugluskr** [diadoc/diadocsdk-java#35]
Добрый день!

Подскажите, как прикрепить стороннюю подпись к существующему документу?

        final DiadocApi api = new DiadocApi("", "");
        api.Authenticate("", "");

        final DocumentsFilter documentsFilter = new DocumentsFilter();
        documentsFilter.boxId = "";
        documentsFilter.filterCategory = "Invoice.Inbound"; 
        documentsFilter.toDocumentDate = "01.09.2016";

        final List<DocumentProtos.Document> list = api.GetDocuments(documentsFilter).getDocumentsList();

        for (final DocumentProtos.Document doc : list) {
            final List<byte[]> signs = outerService.getSigns(doc.getEntityId());

            // тут для каждого документа получаем несколько подписей в виде CMS SignedData в DER из внешнего сервиса, 
            // в результате имеется список из байтмассивов, который нужно прикрепить к документу в диадоке
            // как это сделать?
        }

**Comment by atytsky** [comment]
Привет, что-то затянули с ответом. 

Если документ уже есть в системе, то подпись под документом добавляется с помощью метода [PostMessagePatch](http://api-docs.diadoc.ru/ru/latest/http/PostMessagePatch.html).

**Comment by vugluskr** [comment]
О, отклик :)

Хорошо, а не приведете пример кода, пожалуйста?

**Comment by atytsky** [comment]
Попробуйте посмотреть [примеры](http://api-docs.diadoc.ru/ru/latest/howto/example_torg12.html) использования, например ТОРГ-12.

**Comment by vugluskr** [comment]
Ок, а теперь расскажите пожалуйста, как понимать вот такое сообщение и что делать?

"Команда AddOtherSideSignature не поддерживается документом bd3b8dff-5ba2-4971-974a-8b81db7afecc:2bf43f36-950e-450f-b841-79d445841923"
?

**Comment by atytsky** [comment]
А к какому типу документа хотите добавить ответную подпись?

**Comment by vugluskr** [comment]
Андрей, спасибо за ответы, я закрываю топик, мы общаемся в почте с разработчиком.
Про поддержку подписей у определённых типов документов нам уже рассказали :)
