### ISSUE TITLE
Вопрос по SignatureVerificationResult

### ISSUE THREAD

**Issue by aasmetanin** [diadoc/diadocsdk-java#37]
Добрый день!

Для любого docflow  значение SignatureVerificationResult(http://api-docs.diadoc.ru/ru/latest/proto/SignatureVerificationResult.html) = false. 
В связи с этим не удается получить сертификат в DER-кодировке(getSignature().getVerificationResult().getCertificateStatus().getCertificateChain(0).getDerCertificate()). При этом сами документы и подписи корректны, раньше данный код работал(около 2-3 месяцев назад), ничего не меняли.

//получаем DocFlow по документу
DocflowApiProtos.GetDocflowBatchResponse getDocflows= ...;
SignedAttachment s = getDocflows.getDocuments(0).getDocflow().getDocumentAttachment();//Получаем сущность документа, она непустая
//Далее пытаемся получить сертификат из цепочки, но она пустая. Возникает исключительная ситуация 
ByteString cert = s.getSignature().getVerificationResult().getCertificateStatus().getCertificateChain(0).getDerCertificate(); 

При этом так для любого DocFlow.

Подробности в обращении в тех.поддержку №11450966.

**Comment by atytsky** [comment]
Добрый день.

`SignatureVerificationResult `перенесли под флаг `InjectEntityContent = true`,  по умолчанию флаг  имеет значение `false`. Эту оптимизация сделали для того, что бы уменьшить тело ответа, так как были пожелания от других интеграторов на эту тему.

**Comment by aasmetanin** [comment]
Спасибо! Вопрос решен.
