### ISSUE TITLE
Столкнулись с еще одним исключением при работе с sdk.

### ISSUE THREAD

**Issue by dsurogatov** [diadoc/diadocsdk-java#38]
`org.apache.http.client.HttpResponseException: Access to Box [10469543-4433-4e89-9279-02ac100f1b18] is denied
	at Diadoc.Api.DiadocApi.GetResponseBytes(DiadocApi.java:314)
	at Diadoc.Api.DiadocApi.PerformGetHttpRequest(DiadocApi.java:309)
	at Diadoc.Api.DiadocApi.GetDocuments(DiadocApi.java:911)
`

Что оно обозначает (описания не нашел)?
Возможно, что мы слишком часто посылаем запросы на сервер?

**Comment by asvyazin** [comment]
Просто нет доступа к ящику 10469543-4433-4e89-9279-02ac100f1b18 (a.k.a 1046954344334e89927902ac100f1b18@diadoc.ru) у пользователя, от имени которого вы делаете запрос. Частота запросов тут определенно ни при чем.
