### ISSUE TITLE
Как корректно отправить УПД посредством diadocsdk-java

### ISSUE THREAD

**Issue by PavelZhdanov** [diadoc/diadocsdk-java#42]
Следующий код (его часть)
     
    DiadocMessage_PostApiProtos.MessageToPost.Builder messageBuilder = DiadocMessage_PostApiProtos.MessageToPost.newBuilder(); 
    messageBuilder.setFromBoxId(BOX_ID); 
    messageBuilder.setToBoxId(RECIPIENT_BOX_ID); 
    messageBuilder.setIsDraft(true); 
     
 DiadocMessage_PostApiProtos.XmlDocumentAttachment.Builder attachmentBuilder = messageBuilder.addInvoicesBuilder(); **//какой метод нужно вызывать для УПД???**

    DiadocMessage_PostApiProtos.SignedContent.Builder signedContentBuilder = attachmentBuilder.getSignedContentBuilder(); 
   File file=null; 
   FileInputStream fileStream=new FileInputStream(file=new File("C:\\oraSOA\\mywork\\DiadocWrapperApp\\DiadocWrapperApp\\DiadocWrapperPrj\\src\\diawrapperpkg\\510079.xml")); 
         byte[] content= new byte[(int)file.length()]; 
       fileStream.read(content,0,content.length); 
    signedContentBuilder.setContent(ByteString.copyFrom(content)); 
    DiadocMessage_PostApiProtos.MessageToPost messageToPost = messageBuilder.build(); 
    DiadocMessage_GetApiProtos.Message postedMessage = api2.PostMessage(messageToPost); 
    String postedDraftId = postedMessage.getMessageId(); 
    assertNotNull(postedDraftId); 

выдает ошибку:
Exception in thread "main" org.apache.http.client.HttpResponseException: Невозможно отправить документ с функцией ДОП/СЧФДОП как счёт-фактуру. Измените функцию документа или выберите другой тип документа 
    at Diadoc.Api.DiadocApi.GetResponseBytes(DiadocApi.java:295) 
    at Diadoc.Api.DiadocApi.PerformPostHttpRequest(DiadocApi.java:301) 
    at Diadoc.Api.DiadocApi.PostMessage(DiadocApi.java:176) 
    at diawrapperpkg.diawrapper.main(diawrapper.java:135) 
Picked up _JAVA_OPTIONS: -Xmx512M 
Process exited with exit code 1. 

**Кажется, что надо как-то иначе отправлять УПД, не через addInvoicesBuilder(), возможно, еще где-то иные методы надо использоваться?**

**Comment by halex2005** [comment]
Попробуйте использовать метод addUniversalTransferDocumentSellerTitles для отправки УПД.
