### ISSUE TITLE
PrepareDocumentsToSign в JAVA-библиотеке. Какой метод?

### ISSUE THREAD

**Issue by PavelZhdanov** [diadoc/diadocsdk-java#43]
В документации описан метод PrepareDocumentsToSign (http://api-docs.diadoc.ru/ru/latest/http/PrepareDocumentsToSign.html), пытаемся найти его в diadocsdk-1.39.jar и не находим. Где его можно найти?

**Comment by PavelZhdanov** [comment]
UP!

**Comment by atytsky** [comment]
Метод в SDK добавим на этой неделе.

**Comment by asvyazin** [comment]
Добавили, в версии Sdk 1.41
