### ISSUE TITLE
Не получается создать УПД с функцией СЧФ. Как правильно делать?

### ISSUE THREAD

**Issue by PavelZhdanov** [diadoc/diadocsdk-java#44]
На диаграмме http://api-docs.diadoc.ru/ru/latest/_images/scheme-04-utd-invoice-docflow.png документооборот начинается с документа UTD.
Как я понял, в diadocsdk.jar ему соответствует класс UniversalTransferDocumentInfo. Однако, нет методов для добавления строк товаров. Имеются только следующие методы:

setFunction,
setCurrencyCode,
setGrounds,
setGroundBytes,
setOriginalDocumentDateAndNumber,
setTotal,
setTotalBytes,
setVat,
setVatBytes

В тоже время у класса UniversalTransferDocumentSellerTitleInfo есть метод setInvoiceTable.
В документации в справочнике структур данных http://api-docs.diadoc.ru/ru/latest/protos.html отсутствует структура UniversalTransferDocumentInfo»

**Comment by halex2005** [comment]
Документу UTD соответствует структура [UniversalTransferDocumentSellerTitleInfo](http://api-docs.diadoc.ru/ru/latest/proto/utd/UniversalTransferDocumentSellerTitleInfo.html). Да, у него есть метод setInvoiceTable для добавления строк товаров.

Эту структуру можно передать в метод [GenerateUniversalTransferDocumentXmlForSeller](http://api-docs.diadoc.ru/ru/latest/http/utd/GenerateUniversalTransferDocumentXmlForSeller.html), чтобы сгенерировать формализованный XML-документ.
Полученный формализованный XML-документ вы можете отправить в Диадок методом [PostMessage](http://api-docs.diadoc.ru/ru/latest/http/PostMessage.html).

Вот раздел справочника по API работы с УПД/УКД: http://api-docs.diadoc.ru/ru/latest/API_UniversalTransferDocument.html

Структуру [UniversalTransferDocumentInfo](http://api-docs.diadoc.ru/ru/latest/proto/utd/docflow/UniversalTransferDocumentInfo.html) вы можете получить только для уже заведенного в систему документа УПД с помощью метода [GetDocflows](http://api-docs.diadoc.ru/ru/latest/http/GetDocflows.html).
См. в ответ этого метода [GetDocflowBatchResponse.Documents.DocumentInfo](http://api-docs.diadoc.ru/ru/latest/proto/DocumentInfo.html)
