### ISSUE TITLE
Добавить метод ShelfDownload 

### ISSUE THREAD

**Issue by PavelZhdanov** [diadoc/diadocsdk-java#50]
в SDK версии 1.41.1 нашли метод для генерации архива с документооборотом, но чтобы его скачать нужен метод ShelfDownload, а вот его нет в sdk.
Можно ли добавить ShelfDownload в SDK?

**Comment by halex2005** [comment]
Добавили метод ShelfDownload в релиз [1.41.2](https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F1.41.2)

**Comment by PavelZhdanov** [comment]
Проверили метод ShelfDownload, мы не можем использовать его, т.к. он на вход требует authToken (а остальные методы не требуют). Как мы поняли, authToken выдается раз на сессию и сохраняется в недрах jar,  есть только приватный метод getAuthToken, но вызвать его мы не может (т.к. он приватный). Соответственно, архив получить мы не можем, как нам быть?

**Comment by halex2005** [comment]
Да, copy-paste из diadocsdk-csharp вмешался, действительно параметр authToken там не нужен. Он и не использовался.
Исправил метод [в релизе 1.41.4](https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F1.41.4).
