### ISSUE TITLE
Необходимо задать proxy

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#57]
Где можно задать proxy для установки соединения с Diadoc, используя библиотеку diadocsdk-java?

**Comment by zhirnov-av** [comment]
Где-то год назад, тоже появилась необходимость устанавливать соединение через прокси, решил проблему так:
Скачала исходники, в классе DiadocApi добавил метод:
`
    private static DefaultHttpClient createHttpClientByProxy(String proxyAddress, int port)
            throws NoSuchAlgorithmException, KeyManagementException {
        HttpHost proxy = new HttpHost(proxyAddress, port);
        DefaultHttpClient defaultHttpClient = new DefaultHttpClient();
        defaultHttpClient.getParams().setParameter(ConnRoutePNames.DEFAULT_PROXY, proxy);
        defaultHttpClient = makeTrustfulHttpClient(defaultHttpClient);
        defaultHttpClient.addRequestInterceptor(new DiadocPreemptiveAuthRequestInterceptor(), 0);
        return defaultHttpClient;
    }
`
Потом добавил еще один конструктор класса DiadocApi:
`    public DiadocApi(String apiClientId, String url, String proxyAddress, int port)
            throws KeyManagementException, NoSuchAlgorithmException {
        if (url == null)
            throw new NullPointerException(url);
        this.url = url;
        this.apiClientId = apiClientId;
        this.httpClient = createHttpClientByProxy(proxyAddress, port);
        updateCredentials(null);
    }
`
Потом все собрал, и пользовался вызывая вторую версию конструктора...

**Comment by atytsky** [comment]
#59 влили в мастер.
