### ISSUE TITLE
Отправка УПД. Как добавить в MessageToPost

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#58]
С помощью UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.Builder был создан документ **УПД** (заполнены все нужные поля).

Как правильно добавить этот документ для отправки через MessageToPost
```
DiadocMessage_PostApiProtos.MessageToPost.Builder messBuilder = DiadocMessage_PostApiProtos.MessageToPost.newBuilder();
messBuilder.setFromBoxId(boxFromId);
messBuilder.setToBoxId(boxIdTo);
messBuilder.setIsDraft(true);
```
С помощью метода ```messBuilder.addUniversalTransferDocumentSellerTitles``` добавить объект **UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.Builder** не получается.

P.S. Проблем с добавлением неформализованного документа нет:
```
DiadocMessage_PostApiProtos.NonformalizedAttachment.Builder attBuilder = DiadocMessage_PostApiProtos.NonformalizedAttachment.newBuilder();
...
messBuilder.addNonformalizedDocuments(attBuilder.build());
```

Примеров для javasdk не нашел.

**Comment by halex2005** [comment]
Вы не можете добавить объект `UniversalTransferDocumentSellerTitleInfo` в `MessageToPost`. Этот объект не является формализованным документом УПД, а предназначен для генерации такого документа УПД с помощью метода API `GenerateUniversalTransferDocumentXmlForSeller`.

Сгенерированный этим методом XML-файл УПД вы сможете передать в метод `addUniversalTransferDocumentSellerTitles` используя объект `XmlDocumentAttachment`. В этом объекте нужно заполнить свойство `SignedContent`.

Подробнее про методы API для работы с УПД вы можете прочитать [в документации](http://api-docs.diadoc.ru/ru/latest/API_UniversalTransferDocument.html).

**Comment by kirill-ivanov** [comment]
Спасибо, вопрос решен.
