### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by bastra** [diadoc/diadocsdk-java#6]
Мы делаем отправку следующим образом (часть кода):

                HTTPСоединение = Новый HTTPСоединение("diadoc-api.kontur.ru",,,,,Истина);
                HTTP_Заголовок = Новый Соответствие;
                HTTP_Заголовок.Вставить("host","diadoc-api.kontur.ru");
                HTTP_Заголовок.Вставить("Connection","Keep-Alive");
                ЗаголовокДляАвторизации = "DiadocAuth ddauth_api_client_id="+TokenApi+" ddauth_token="+TokenSession;
                HTTP_Заголовок.Вставить("Authorization",ЗаголовокДляАвторизации);
                ИмяРесурса = "GenerateInvoiceXml?invoiceType=Invoice";
                HTTPЗапрос = Новый HTTPЗапрос(ИмяРесурса, HTTP_Заголовок);
                HTTPЗапрос.УстановитьТелоИзСтроки(JSON, "UTF-8");

Естественно, ключ разработчика и токен мы вставляем корректный.
Ответ вашего сервиса: Код 400, Can't deserialize request body into type: InvoiceInfo

В аттаче- JSON

[example.txt](https://github.com/diadoc/diadocsdk-java/files/359161/example.txt)

**Comment by halex2005** [comment]
Для выполнения запроса, в теле которого идет JSON, необходимо указать заголовок `Content-Type`. В указанном примере, видимо, не хватает строки:

    HTTP_Заголовок.Вставить("Content-Type","application/json charset=utf-8");

Без этого заголовка тело запроса считается protobuf-структурой, а не JSON. Поэтому вы получаете указанную ошибку.

При беглом осмотре JSON-аттача, заметил что у вас неверно указаны параметры Seller.BoxId и Buyer.BoxId: в них задан идентификатор участника ЭДО, что не является корректным значением для этого параметра. Там должен содержаться GUID ящиков продавца и покупателя, а не идентификатор ЭДО.

Для идентификатора ЭДО в структуре `OrganizationInfo` есть поле `FnsParticipantId`.
