### ISSUE TITLE
Исключение при работе с парой методов AutoSignReceipts/WaitAutosignReceiptsResult

### ISSUE THREAD

**Issue by bovin-a** [diadoc/diadocsdk-java#61]
Используем облачные подписи и после первого подписания и отправки СЧ или УПД с функцией СЧ хотим запустить автоматическое подписание служебных сообщений от оператора ЭДО. Для этого делаем пару вызовов обозначенных выше методов:
```
AsyncMethodResult autoSignResult = diadocApi.AutoSignReceipts(boxId, null, null);
AutosignReceiptsResult receiptsResult = diadocApi.WaitAutosignReceiptsResult(autoSignResult.getTaskId(), Integer.MAX_VALUE);
```
Но второй метод падает с исключением:
```
[error] application - Message missing required fields: NextBatchKey, SignedReceiptsCount
com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: NextBatchKey, SignedReceiptsCount
at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
at Diadoc.Api.Proto.CloudSignProtos$AutosignReceiptsResult.parseFrom(CloudSignProtos.java:2800)
at Diadoc.Api.DiadocApi.WaitAutosignReceiptsResult(DiadocApi.java:1292)
```
Используем Java SDK версии 1.45.1. Подскажите, как с этим быть. Пока приходится вручную подписывать все служебные документы, что приводит к получению двух подряд СМС с кодом.

**Comment by bovin-a** [comment]
Удалось воспроизвести? Есть ли примерная оценка по времени, когда может быть исправлено?

**Comment by atytsky** [comment]
Воспроизвести не удалось. Видимо только 200 и 204 коды ответа.

Какой код ошибки получаете? Со всеми _taskId_ такая ошибка или только с одним?

**Comment by bovin-a** [comment]
Ошибка со всеми taskId. HTTP код ответа 200, но при этом данных в ответе нет, что приводит в дальнейшем к ошибке при выполнении строки

`AutosignReceiptsResult.parseFrom(data);`

т.к. data представляет из себя пустой массив байт.

Скрин http://joxi.ru/BA00xa8SJ7zLbA

**Comment by atytsky** [comment]
Ошбика в SDK, в контракте:
```
message AutosignReceiptsResult {
    required string NextBatchKey = 1;
    required int32 SignedReceiptsCount = 2;
}
```
 _NextBatchKey_ не является обязательным, если ничего не подписалось, возвращается структура вида

```
{
    "SignedReceiptsCount": 0
}
```

Поправим на этой неделе.

**Comment by bovin-a** [comment]
Есть продвижение?

**Comment by bovin-a** [comment]
Коллеги, использование

**Comment by atytsky** [comment]
Исправлено в #79
