### ISSUE TITLE
Ошибка при авторизации по ключу java.security.NoSuchAlgorithmException: GOST3410DH KeyFactory not available

### ISSUE THREAD

**Issue by RunProg** [diadoc/diadocsdk-java#62]
Здравствуйте. Я разрабатываю приложения для интеграции DiadocApi с ERP системой предприятия. Для проверки авторизации написал следующий код:
```
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.logging.Level;
import java.util.logging.Logger;

import Diadoc.Api.DiadocApi;

public class Main {
	
	private static Logger log = Logger.getLogger(Main.class.getName());
	
	static String apiClientId="uralati-11111111-1111-1111-1111-111111111111";
	static String url="https://diadoc-api.kontur.ru";
	static String pathToCert="D:/MyDoc/Work/CryptoProCer/ati20170.000/ati201705.cer";
	
	public static void main(String[] args){
		try {
			DiadocApi diadocApi = new DiadocApi(apiClientId,url);
			X509Certificate diadocCertificate = readCertContent(pathToCert);	
			try {
				diadocApi.Authenticate(diadocCertificate);
			} catch (Exception e) {
				log.log(Level.SEVERE, "Exception: ", e);
			}
		} catch (KeyManagementException e) {
			log.log(Level.SEVERE, "Exception: ", e);
		} catch (NoSuchAlgorithmException e) {
			log.log(Level.SEVERE, "Exception: ", e);
		}
		
	}
	

	private static X509Certificate readCertContent(String pathToCert)
	{
		InputStream certInputstream;
		X509Certificate cert = null;
		try {
			certInputstream = new FileInputStream(pathToCert);
			CertificateFactory cf = CertificateFactory.getInstance("X.509");
			cert = (X509Certificate) cf.generateCertificate(certInputstream);
		} catch (FileNotFoundException | CertificateException e) {
			log.log(Level.SEVERE, "Exception: ", e);
		}
		return cert;
	}
	
}
```
Значение переменной apiClientId в листинге изменено, при тестировании переменной присваивается значение полученное по электронной почте от Диадок.
При попытке запустить приложение появляется сообщение об ошибке:
```
авг 01, 2017 2:42:11 PM Main main
SEVERE: Exception: 
java.security.NoSuchAlgorithmException: GOST3410DH KeyFactory not available
	at java.security.KeyFactory.<init>(Unknown Source)
	at java.security.KeyFactory.getInstance(Unknown Source)
	at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:276)
	at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:232)
	at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:189)
	at Main.main(Main.java:27)
```
Версия ОС:
`Microsoft Windows [Version 6.1.7601] x64`
Версия Java:
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```
Версия JCP:
`jcp-2.0.39014`
Версия diaidoc-sdk:
`diadocsdk-1.45.1`
Подскажи, пожалуйста, как я могу исправить указанную ошибку ?

**Comment by antigravity** [comment]
Есть что-то необычное в диагностике JCP?
```java
java -cp samples.jar ComLine.CheckConfFull
```

**Comment by RunProg** [comment]
Да, при запуске диагностики появляется сообщение "Ключи ГОСТ Р 34.10-2001 нельзя использовать для выработки подписи...". Полный текст сообщения на прикрепленном снимке экрана [http://www.picshare.ru/view/8225740/](url)

**Comment by antigravity** [comment]
Эта странная ошибка означает, что Крипто Про не нашла секретный ключ выбранного сертификата - он нужен, когда сертификатом что-то подписывают или авторизуются.

Секретный ключ устанавливается локально в хранилище Крипто Про. К сожалению у Крипто Про для Java свое хранилище, отличное от хранилища обычного Крипто Про, поэтому, даже если в системе как будто бы уже установлен этот сертификат, и он даже работает, например, в браузере, то все-равно Java Крипто Про может его не видеть.

Если секретный ключ сертификата находится на флешке, то его можно просто скопировать в хранилище Java, которое по-умолчанию находится в _C:\Users\<имя пользователя>\AppData\Local\Crypto Pro_.

Обычно секретный ключ - это директория с именем типа **ivanov-20.000**, всю директорию надо скопировать как есть. Либо можно в настройках Java Крипто Про поменять путь к хранилищу, указав путь к флешке, тогда можно ничего не копировать.

Утилита для редактирования настроек запускается батником ControlPane.bat или ControlPane.sh (распространяется вместе с Java Крипто Про), нужно при запуске передать в качестве параметра полный путь к JRE.

Если секретный ключ - в реестре, то надо сначала выгрузить его на флешку.

**Comment by RunProg** [comment]
Скопировал папку с сертификатом в директорию КриптоПРО 

C:\Users\prog06\AppData\Local\Crypto Pro\ati20170.000

Открыл утилиту для редактирования настроек КриптоПРО JSP

ControlPane.bat D:\Program\Java\jdk1.8.0_144\jre

На вкладке "Keys and certificates stores" в левом верхнем углу в пункте "Container Stores" в подпункте "HDImageStore" отображается 3 пункта, один из них "ati201705".

http://www.picshare.ru/view/8226181/

В Java приложении изменил значение переменной на путь к новому сертификату:

static String pathToCert="C:/Users/prog06/AppData/Local/Crypto Pro/ati20170.000/ati201705.cer";

Java приложение для проверки авторизации также не запускается (Сообщение об ошибке не поменялось).

И при вызове команды:
D:\Program\Java\jdk1.8.0_144\jre\bin>java -cp samples.jar ComLine.CheckConfFull

также появляется сообщение "Ключи ГОСТ Р 34.10-2001 нельзя использовать для выработки подписи..."
Подскажите, пожалуйста, как я еще могу проверить путь к сертификату, который использует КриптоПРО JCP ?
Возможно сертификат должен отображаться в области "Sertificate stores" в утилите для редактирования настроек КриптоПРО JSP ?

**Comment by antigravity** [comment]
@RunProg 

В каталоге _C:/Users/prog06/AppData/Local/Crypto Pro/ati20170.000/_ должен находится приватный ключ.

Содержимое каталога должно выглядеть примерно так:

![photo_2017-08-10_12-53-25](https://user-images.githubusercontent.com/168414/29160279-1309b9de-7dcb-11e7-9aa3-1538be993cb8.jpg)

В случае, если сертификат не железный, то необходимо экспортировать приватный ключ из Крипто Про на железный носитель, а затем скопировать его содержимое в каталог _C:/Users/prog06/AppData/Local/Crypto Pro/ati20170.000/_.

**Comment by RunProg** [comment]
Проверил содержимое каталога C:\Users\prog06\AppData\Local\Crypto Pro\ati20170.000 , в нем действительно находятся все перечисленные файлы:

![img3](https://user-images.githubusercontent.com/30623085/29162395-bf147726-7dd2-11e7-943b-fac079356d0b.jpg)

, но ошибка в Java приложении все равно появляется и при вызове команды:
D:\Program\Java\jdk1.8.0_144\jre\bin>java -cp samples.jar ComLine.CheckConfFull

также появляется сообщение "Ключи ГОСТ Р 34.10-2001 нельзя использовать для выработки подписи...".
Может кроме копирования, ключ еще должен быть установлен через приложение "Крипто ПРО CSP" или я пропустил какие-то еще действия ?

**Comment by alogicman** [comment]
А какая версия Крипто ПРО используется?

**Comment by RunProg** [comment]
Версию КриптоПРО просмотрел в "Пуск\ Все программы\ КРИПТО-ПРО\ КриптоПро CSP"
Версия 4.0.9842 (Прикрепил снимок экрана)
![img4](https://user-images.githubusercontent.com/30623085/29167971-3f0d6a24-7de6-11e7-9471-77ae9c020755.jpg)

**Comment by alogicman** [comment]
А можно скрины вкладок Безопасность и Алгоритмы посмотреть?

**Comment by RunProg** [comment]
Вкладка "Безопасность"

![img6](https://user-images.githubusercontent.com/30623085/29168698-73a308a4-7de9-11e7-99fa-dc7b2e9fc203.jpg)

Вкладка "Алгоритмы"

![img7](https://user-images.githubusercontent.com/30623085/29168708-7bec04c0-7de9-11e7-98dc-9389e96d5e9e.jpg)

**Comment by alogicman** [comment]
В настройках все нормально вроде

> Может кроме копирования, ключ еще должен быть установлен через приложение "Крипто ПРО CSP" или я пропустил какие-то еще действия?

Да, закрытый ключ через Крипто Про надо установить - на вкладке Сервис

**Comment by pavel-vp** [comment]
Добрый день. У меня точно такая же ситуация и точно такая же ошибка. Но этот сертификат  успешно использую для подписания при интеграции с другим провайдером. А с ДиаДок не получается.
Я увидел, что в методе авторизации явно указано имя алгоритма - 
        KeyFactory kf = KeyFactory.getInstance("GOST3410DH");
А в файле JCP.class - такого алгоритма нет.
Еще в примерах КриптоПро нашел такой кусок кода -
  put("GOST3410",   Consts.URI_GOST_SIGN); // < JCP 2.0
  put("GOST3410DH", Consts.URI_GOST_SIGN); // < JCP 2.0

это что значит этот алгоритм был доступен только в JCP ниже 2.0 ?
То есть для использования SDK ДиаДок нужен JCP ниже 2.0 ?

**Comment by asvyazin** [comment]
> То есть для использования SDK ДиаДок нужен JCP ниже 2.0 ?
Вот это вполне возможно, код тестировался только на версии 1.0. До недавнего времени JCP 2.0 не было сертифицировано ФСБ, поэтому мы его и не поддерживали, но оказывается с 30.12.2016 уже есть сертификат ФСБ и на JCP 2.0

**Comment by pavel-vp** [comment]
И что посоветуете? Ставить JCP 1.0 или можно подождать изменений?

**Comment by pavel-vp** [comment]
Похоже проблема с установкой JCP версии ниже 2.0 на Java 7 и выше. Так что вопрос о совместимости SDK Диадок с JCP 2.0 очень актуален

**Comment by alogicman** [comment]
> И что посоветуете? Ставить JCP 1.0 или можно подождать изменений?

Если критично, то лучше не ждать

**Comment by RunProg** [comment]
Вы можете, примерно, сориентировать по срокам - когда вы планируете добавить совместимость SDK Диадок с JCP 2.0 ?

**Comment by antigravity** [comment]
@RunProg @pavel-vp 

Проверьте, установлен ли [JCE](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) и содержаться ли в classpath пакеты JCP*.

**Comment by RunProg** [comment]
Скачал по указной ссылке и скопировал в папку jcp (D:\Program\Java\jdk1.8.0_144\jre\bin) два файла local_policy.jar и US_export_policy.jar.
Я думаю, что пакеты JCP* содержатся в classpath т.к. до установки JCP сообщение об ошибке в окне Console Eclipse было NoClassDefFoundError:
![img8](https://user-images.githubusercontent.com/30623085/29491865-abd0e3fe-8582-11e7-95de-91c455dd9b42.jpg)
т.е. отсутствовал класс описанный в JCP, а после установки JCP текст ошибки поменялся на NoSuchAlgorithmException:
![img9](https://user-images.githubusercontent.com/30623085/29491871-baf7189e-8582-11e7-88c7-9275e7ed6400.jpg)
При установки JCP выбрана именно та папка с JDK с помощью которой происходит отладка приложения в Eclipse (На снимках экрана указан путь к JDK).
![img10](https://user-images.githubusercontent.com/30623085/29491873-c6ce29d2-8582-11e7-8dc4-792f06af7c22.jpg)
В исходных кодах Диадок, в файле .\diadocsdk-java-versions-1.45.1\diadocsdk-java-versions-1.45.1\src\main\java\Diadoc\Api\DiadocApi.java, в строке 176 (KeyFactory kf = KeyFactory.getInstance(JCP.GOST_DH_NAME);)  Есть обращение к полю JCP.GOST_DH_NAME, на форуме КриптоПРО (https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=9140) указано, что поля JCP.GOST_DH_NAME нет начиная с JCP 2.0.37748.
Я думаю, что проблемы не в отсутствии JCP в classpath, а в том, что выше написал asvyazin: 

>  Вот это вполне возможно, код тестировался только на версии 1.0. До недавнего времени JCP 2.0 не было сертифицировано ФСБ, поэтому мы его и не поддерживали, но оказывается с 30.12.2016 уже есть сертификат ФСБ и на JCP 2.0

Возможно pavel-vp столкнулся с такой же ошибкой. И поэтому я хотел бы уточнить - когда, примерно, вы планируете добавить совместимость SDK Диадок с JCP 2.0 ?

**Comment by pavel-vp** [comment]
@RunProg 
Мне не удалось заставить работать JCP 2.0 c СДК Диадока и Java 1.8.
Поэтому установил следующую конфигурацию - JCP 1.054 + JRE 1.7.017
и СДК Диадока заработал.

**Comment by AnthonyDakota** [comment]
@RunProg 
Пробовал установить конфигурацию как у вас , но диадок так и не заработал. Не удается пройти аутентификацию по сертификату . Сертификат получаю  из "RutokenStore".  "Ошибки
 Algorithm GOST3410DHEL not available
Параметры ключа не соответствуют алгоритмам подписи ГОСТ и обмена Диффи-Хелмана".
Никто не подскажет в чем может быть проблема ?

**Comment by RunProg** [comment]
@AnthonyDakota 
Я использую версии JCP и JRE такие как предложил @pavel-vp (Спасибо большое, мне это решение помогло). С более новыми версиями JCP, мне кажется, что DiadocApi не совместим на данный момент (т.к. DiadocApi обращается к константе GOST3410DH, а ее нет в новых версиях JCP).
В issues есть решение проблемы, похожей на ту которую вы описали ("Параметры ключа не соответствуют алгоритмам подписи ГОСТ и обмена Диффи-Хелмана"),
[вот ссылка](https://github.com/diadoc/diadocsdk-java/issues/1)

**Comment by sharykin** [comment]
Здравствуйте.
Я разрабатываю интеграции ERP системы с Диадок. Для этого хочу использовать diadocsdk-java.
Однако, код, аналогичный указанному в заголовке темы, выдает ошибку, указанную в теме: java.security.NoSuchAlgorithmException: GOST3410DH KeyFactory not available.
Я использую diadocsdk версии 1.51.5.
Как я понял из обсуждения выше, диадок использует константу GOST3410DH, которая отсутствует в JCP 2.0.39014 (последняя лицензированная версия).
В своем приложении я не могу использовать более ранние версии JCP, так как они требуют java < 1.8, а ERP требует java 1.8.
У меня два вопроса:
1. Возможно ли на текущий момент использовать diadocsdk с JCP 2.0.39014?
2. Когда можно ожидать обновления diadocsdk?
Заранее спасибо.
