### ISSUE TITLE
УПД в формате СЧФ с визуализацией счет-фактуры

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#68]
Если УПД указать функцию (тип) СЧФ, форма все равно визуализируется как счет-фактура+передаточный акт (1).
Можно ли при отправке УПД в формате СЧФ указать, чтобы она визуализировалась как счет-фактура?

**Comment by alogicman** [comment]
Вы можете отправлять СФ в формате УПД СЧФ. Визуализация и печатная форма в этом случае будет от СФ. Такой вариант подойдёт? Или документ принципиально по типу нужен УПД?

**Comment by kirill-ivanov** [comment]
Нужно как раз УПД, но чтобы отображение как обычная счет-фактура.

**Comment by atytsky** [comment]
Сейчас визуализация зависит от типа документа, который используется при отправке. Изменений в визуализации не планируется.
