### ISSUE TITLE
Новая форма с/ф с 01.10.2017

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#73]
Добрый день.
На сайте есть новость о новом формате с/ф с 01.10.2017
https://www.diadoc.ru/blog/7776

Документ должен вступить в силу к 01.10.2017, но пока еще не вступил.
http://www.consultant.ru/document/cons_doc_LAW_223158/

Что-нибудь поподробнее можно узнать? Предусмотрены ли доработки в Диадоке?

**Comment by atytsky** [comment]
С 01.10 октября Диадок поддержит данные изменения в превью и печатных формах.

[Еще](https://www.diadoc.ru/blog/7782) информация.
