### ISSUE TITLE
Подписанные данные были искажены после момента подписания.

### ISSUE THREAD

**Issue by AnthonyDakota** [diadoc/diadocsdk-java#78]
Здравствуйте.
Столкнулся с такой проблемой при подписании документа. 
API никаких ошибок не возвращает, а в вебе ошибка.

`     
 requestedSignaturesBuilder.setParentEntityId(currentDocument.getEntityId());                        requestedSignaturesBuilder.setSignature(ByteString.copyFrom(currentDocument.getContent().toByteArray()));
                        requestedSignatures = requestedSignaturesBuilder.build();                        
                        msgPatchToPostBuilder.addSignatures(requestedSignatures);
                        msgPatchToPostBuilder.setBoxId(iFromBoxId);
                        msgPatchToPostBuilder.setMessageId(currentDocument.getMessageId());
                        msgPatchToPost = msgPatchToPostBuilder.build();    
                        msgPatch = diadocApi.PostMessagePatch(msgPatchToPost);`

**Comment by atytsky** [comment]
По примеру кода непонятно, как вы подписываете документ. Для подписания в SDK есть [CertificateHelper](https://github.com/diadoc/diadocsdk-java/blob/master/src/main/java/Diadoc/Api/CertificateHelper.java)

**Comment by AnthonyDakota** [comment]
@atytsky 
Здравствуйте. 
Попробовал использовать api, документ подписал , но при отправку в веб там все равно ошибка.
Как должны быть наполнен структуры что бы документ после подписания сохранился без ошибок. 
  RequestedSignatures = null;
  RequestedSignatures = new DocumentSignature();
  RequestedSignatures.ParentEntityId = CurrentDocument.EntityId;
  RequestedSignatures.Signature = Crypt.Sign(CurrentDocument.Content.Data, CurrentCert.RawData);
  MsgPatchToPost.AddSignature(RequestedSignatures);
это код для C#  он работает.  
как выполнить эту же операцию на java ?

**Comment by atytsky** [comment]
В C# коде у вас явно есть криптографическая операция:
`RequestedSignatures.Signature = Crypt.Sign(CurrentDocument.Content.Data, CurrentCert.RawData)`.

В Java коде вы в подпись передаете контент документа:
`requestedSignaturesBuilder.setSignature(ByteString.copyFrom(currentDocument.getContent().toByteArray()))`

Ошибка `Подписанные данные были искажены после момента подписания` говорит о том, что вы все сделали правильно, но контент подписи не соответствует файлу.

Попробуйте создать подпись с помощью метода [Sign](https://github.com/diadoc/diadocsdk-java/blob/master/src/main/java/Diadoc/Api/CertificateHelper.java#L118)

**Comment by AnthonyDakota** [comment]
@atytsky 
не работает.
документ подписан, но ошибка осталась . 
В чем может быть еще проблема ? 
`                

                       DiadocMessage_PostApiProtos.DocumentSignature.Builder
                       documentSignatureBuilder;
                       documentSignatureBuilder
                       = DiadocMessage_PostApiProtos.DocumentSignature.newBuilder();
                       DiadocMessage_PostApiProtos.DocumentSignature documentSignature = null;                       
                       signedContentBuilder.setContent(ByteString.copyFrom(
                       currentDocument.getContent().toByteArray()));
                       signedContent = signedContentBuilder.build();
                       documentSignatureBuilder.setParentEntityId(currentDocument.getEntityId());

                        try {
                            byte[] docSign = CertificateHelper.sign(x509Certificate, signedContent.getContent().toByteArray());
                            documentSignatureBuilder.setSignature(ByteString.copyFrom(docSign));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                        documentSignature = documentSignatureBuilder.build();
                        msgPatchToPostBuilder.addSignatures(documentSignature);
                        msgPatchToPostBuilder.setBoxId(iFromBoxId);
                        msgPatchToPostBuilder.setMessageId(currentDocument.getMessageId());
                        msgPatchToPost = msgPatchToPostBuilder.build();`

**Comment by AnthonyDakota** [comment]
Вопрос не актуален. Решение найдено.

**Comment by Nikkkb** [comment]
> Вопрос не актуален. Решение найдено.

А какое решение то подскажите?

**Comment by georgynt** [comment]
Тоже бы очень хотелось выяснить в чём была проблема. Сталкнулся с тем же самым. Но код на python и использую метов SignCades

**Comment by AnthonyDakota** [comment]
> (͡°͜ʖ͡°) в аду есть отдельный котёл для таких людей ))) (шучу) (насчет - Вопрос не актуален. Решение найдено. ) - а какое решение то ?

Ниче вы приколисты . Если правильно помню, то проблема была в самом сертификате которым подписывал . Система не могла получить доступ к флешке на которой находился сертификат . И получалось так что несколько прогонов работает , а потом могло перестать работать . Причем эта проблема была только на Java Linux. В винде с c# все хорошо .

**Comment by rivigor2** [comment]
> > (͡°͜ʖ͡°) в аду есть отдельный котёл для таких людей ))) (шучу) (насчет - Вопрос не актуален. Решение найдено. ) - а какое решение то ?
> 
> Ниче вы приколисты . Если правильно помню, то проблема была в самом сертификате которым подписывал . Система не могла получить доступ к флешке на которой находился сертификат . И получалось так что несколько прогонов работает , а потом могло перестать работать .

Спасибо (͡°͜ʖ͡°) извиняюсь если грубо вышло с шуткой ))) 
- делаю тоже интеграцию, намучился, такого же рода была ошибка, решил - у меня проблема была в том что различались данные в Content которые были подписанные (Signature) и в самом Content (мой косяк по невнимательности)
