### ISSUE TITLE
Структура Signature

### ISSUE THREAD

**Issue by bastra** [diadoc/diadocsdk-java#8]
При отправке счета-фактуры используется структура MessageToPost, в которую нужно положить следующие атрибуты:
значение атрибута FromBoxId, 
значение атрибута ToBoxId 
для передачи XML-файла СФ/ИСФ/КСФ/ИКСФ нужно использовать атрибут Invoices, описываемый структурой XmlDocumentAttachment
внутри структуры XmlDocumentAttachment находится вложенная структура SignedContent,
сам XML-файл нужно передать в атрибут Content, подпись продавца в атрибут Signature.
По описанию API в структуре данных SignedContent есть параметр Signature - ЭЦП. Если ЭЦП присутствует, то она должна быть представлена в формате CMS SignedData в DER-кодировке.
Вопрос:
Есть ли пример преобразования ЭЦП в формат CMS SignedData в DER-кодировке? Какой параметр нужно брать из данных сертификата для преобразования в бинарный массив?  И что после преобразования нужно подставлять в структуру?
В общем, буду благодарна если вы предоставите наглядный пример кода.
Заранее спасибо.

**Comment by halex2005** [comment]
В diadocsdk-java входит класс CertificateHelper, с помощью методов которого можно получить X509-сертификат:

    byte[] certBytes = ...; 
    X509Certificate cert = CertificateHelper.GetCertificateFromBytes(certBytes);
    // можно также использовать метод CertificateHelper.GetCertificatesFromPersonalStore()
    // чтобы получить все сертификаты персонального хранилища и выбирать из них

Предположим, что содержимое XML-файла СФ/ИСФ/КСФ/ИКСФ лежит в fileBytes, тогда подписать их сертификатом можно также с помощью класса CertificateHelper:

    byte[] fileBytes = ...;
    byte[] signature = CertificateHelper.sign(cert, invoiceContent);

Вот пример отправки подписанных данных (исползуется fileBytes и signature из примера выше) с помощью метода API PostMessage:

    DiadocMessage_PostApiProtos.MessageToPost.Builder invoiceBuilder = DiadocMessage_PostApiProtos.MessageToPost.newBuilder();
    invoiceBuilder.setFromBoxId(BOX_ID);
    invoiceBuilder.setToBoxId(RECIPIENT_BOX_ID);

    DiadocMessage_PostApiProtos.XmlDocumentAttachment.Builder invoiceAttachmentBuilder = invoiceBuilder.addInvoicesBuilder();
    DiadocMessage_PostApiProtos.SignedContent.Builder signedContentBuilder = invoiceAttachmentBuilder.getSignedContentBuilder();
    signedContentBuilder.setContent(ByteString.copyFrom(fileBytes));
    signedContentBuilder.setSignature(ByteString.copyFrom(signature));

    DiadocMessage_PostApiProtos.MessageToPost messageToPost = invoiceBuilder.build();
    DiadocMessage_PostApiProtos.Message postedInvoice = api.PostMessage(messageToPost);
