### ISSUE TITLE
Получение истории по документам

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#87]
Подскажите, как с помощью java sdk, зная 
   **boxId** отправителя
   **messageId** отправки,
получить цепочку действий, которые происходили с комплектом документов (история).
![diadoc](https://user-images.githubusercontent.com/5112746/35110555-2144d766-fc8a-11e7-8fbe-4e6aefb59b62.png)

**Comment by i82** [comment]
Добрый день. Извиняемся за долгий ответ. Вопрос еще актуален?

**Comment by antigravity** [comment]
@kirill-ivanov На данный момент возможность получения истории в API отсутствует.
