### ISSUE TITLE
проблема с сериализатором Json

### ISSUE THREAD

**Issue by bastra** [diadoc/diadocsdk-java#9]
Возникла проблема с сериализатором Json на платформе 1с 8.2.
Сформированный файл отправляем в сервис и получаем в ответ xml с поплывшей кодировкой. 

Файл запрос и ответ во вложении.

[Ответ в xml.txt](https://github.com/diadoc/diadocsdk-java/files/365536/xml.txt)
[Пример запроса.txt](https://github.com/diadoc/diadocsdk-java/files/365535/default.txt)

**Comment by atytsky** [comment]
@bastra вопрос про 1С лучше задать [здесь](https://github.com/diadoc/diadocsdk-1c-docs)
